# @import ./login.http
# @import ./magazines.http

###
# @name create_issue
# @ref login
# @ref create_magazine
POST {{host}}/api/issues
Authorization: Bearer {{login.access_token}}

{
  "data": {
    "magazine_id": {{create_magazine}},
    "number": 1,
    "count": 1,
    "year": 2023
  }
}
?? status == 201