Table Publisher {
        id int [pk, increment]
        name varchar
        fullname varchar
}

Table Author {
        part_id int [ref: > Part.id]
        person_id int [ref: > Person.id]
}	
        
Table Translator {
        part_id int [ref: > Part.id]
        person_id int [ref: > Person.id]
}	
        
Table Editor {
        edition_id int [ref: > Edition.id]
        person_id int [ref: > Person.id]
}	
        
Table Pubseries {
        id int [pk, increment]
        name varchar
        publisher_id int [ref: > Publisher.id]
        important boolean
}	
        
Table Bookseries {
        id int [pk, increment]
        name varchar
        important boolean
}	
        
Table Person {
        id int [pk, increment]
        name varchar
        alt_name varchar
        first_name varchar
        last_name varchar
        image_src_url varchar
        image_src varchar
        dob varchar
        dod varchar
        bio varchar
        bio_src varchar
        birthplace varchar
        other_names varchar
        imported_string varchar
}	
        
Table Alias {
        alias int [ref: > Person.id]
        real_name int [ref: > Person.id]
}	
        
Table Work {
        id int [pk, increment]
        title varchar
        subtitle varchar
        pubyear int
        language varchar
        bookseries_id int [ref: > Bookseries.id]
        bookseriesnum varchar
        bookseriesorder int
        collection boolean
        image_src varchar
        image_src_url varchar
        description varchar
        misc varchar
        imported_string varchar
        creator_str varchar
}	
        
Table Edition {
        id int [pk, increment]
        title varchar
        subtitle varchar
        pubyear int
        translation boolean
        language varchar
        publisher_id int [ref: > Publisher.id]
        editionnum int
        image_src varchar
        image_src_url varchar
        isbn varchar
        pubseries_id int [ref: > Pubseries.id]
        pubseriesnum int 
        collection boolean
        coll_info varchar
        pages int
        cover varchar
        binding varchar
        description varchar
        misc varchar
        imported_string varchar
}	
        
Table User {
        id int [pk, increment]
        name varchar
        password_hash varchar
        is_admin boolean
        language varchar
}	
        
Table UserBook {
        edition_id int [ref: > Edition.id]
        user_id int [ref: > User.id]
}	

Table UserPubseries {
        pubseries_id int [ref: > Pubseries.id]
        user_id int [ref: > User.id]
} 
        
Table UserBookseries {
        bookseries_id int [ref: > Bookseries.id]
        user_id int [ref: > User.id]
} 
        
Table Part {
        id int [pk, increment]
        edition_id int [ref: > Edition.id]
        work_id int [ref: > Work.id]
        shortstory_id int [ref: > ShortStory.id]
        title varchar
}	

Table ShortStory {
        id int [pk, increment]
        title varchar
        language varchar
        pubyear int
        creator_str varchar
}	

Table StoryGenre {
        shortstory_id int [ref: > ShortStory.id]
        name varchar
}
        
Table Genre {
        work_id int [ref: > Work.id]
        name varchar
}	

Table Award {
        id int [pk, increment]
        name varchar
        type varchar
        description varchar
} 
       
Table Awarded {
        id int [pk, increment]
        award_id int [ref: > Award.id]
        person_id int [ref: > Person.id]
        work_id int [ref: > Work.id]
        story_id int [ref: > ShortStory.id]
} 
       
Table Tag {
        id int [pk, increment]
        tag varchar
        user_id int [ref: > User.id]
        target varchar
        target_id int
} 
        
Table Magazine {
        id int [pk, increment]
        name varchar
        publisher_id int [ref: > Publisher.id]
        issn varchar
} 
        
Table Issue {
        id int [pk, increment]
        magazine_id int [ref: > Magazine.id]
        number int
        year int
} 

Table PersonLink {
  id int [pk, increment]
  person_id int [ref: > Person.id]
  link varchar
  description varchar
}

Table WorkLink {
  id int [pk, increment]
  work_id int [ref: > Work.id]
  link varchar
  description varchar
}

Table EditionLink {
  id int [pk, increment]
  edition_id int [ref: > Edition.id]
  link varchar
  description varchar
}

Table BookseriesLink {
  id int [pk, increment]
  bookseries_id int [ref: > Bookseries.id]
  link varchar
  description varchar
}

Table PubseriesLink {
  id int [pk, increment]
  pubseries_id int [ref: > Pubseries.id]
  link varchar
  description varchar
}

Table PublisherLink {
  id int [pk, increment]
  publisher_id int [ref: > Publisher.id]
  link varchar
  description varchar
}
