#!/bin/bash

echo Importing bibliography
python bib_import.py

#echo Importing multi-part books
#python bib_import.py --multipart

echo Importing short stories
python import_stories.py

echo Importing magazines
python import_magazines.py

echo Importing awards
python import_awards.py

echo Importing showroom
python bib_import.py --showroom

echo Importing images
python import_images.py
