genres_list = {'F' : 'F',
          'K' : 'K',
          'Paleof' : 'Paleof',
          'paleof' : 'Paleof',
          'PF' : 'PF',
          'SF' : 'SF',
          'VEH' : 'VEH',
          'utopia' : 'Utopia',
          'nF' : 'nF',
          'nSF' : 'nSF',
          'nSf' : 'nSF',
          'nK' : 'nK',
          'lasten SF' : 'lSF',
          'satu' : 'satu',
          'ei-sf' : 'eiSF',
          'eiSF' : 'eiSF',
          'eisf' : 'eiSF',
          'rajatap' : 'rajatapaus'
          }
