translators =\
        [
        ('Aulis Rantasen työryhmä', 'Aulis Rantasen työryhmä', ''),
        ('Biokustannuksen käännösryhmä', 'Biokustannuksen käännösryhmä', ''),
        ('Turun yliopiston suomentajaseminaari', 'Turun yliopiston suomentajaseminaari', ''),
        ('A. Peromies', 'A.', 'Peromies'),
        ('A. Tiusanen', 'A.', 'Tiusanen'),
        ('Aarne A. Astala', 'Aarne A.', 'Astala'),
        ('Aarne T.K. Lahtinen', 'Aarne T.K.', 'Lahtinen'),
        ('A.M. Anttila', 'A.M.', 'Anttila'),
        ('E-L. Manner', 'E-L.', 'Manner'),
        ('E. Heikkinen', 'E.', 'Heikkinen'),
        ('E. Kivikkaho', 'E.', 'Kivikkaho'),
        ('E. Leikoski', 'E.', 'Leikoski'),
        ('H. Järvenpää', 'H.', 'Järvenpää'),
        ('E. Palsbo', 'E.', 'Palsbo'),
        ('H. Nurminen', 'H.', 'Nurminen'),
        ('Hugo L. Mäkinen', 'Hugo L.', 'Mäkinen'),
        ('J.K. Ihalainen', 'J.K.', 'Ihalainen'),
        ('J. Konkka', 'J.', 'Konkka'),
        ('J. Linturi', 'J.', 'Linturi'),
        ('J. K. Ihalainen', 'J. K.', 'Ihalainen'),
        ('J. Säilä \(Judén\)', 'J.', 'Säilä (Judén)'),
        ('Jaakko V. Tapio', 'Jaakko V.', 'Tapio'),
        ('K.V. Raitio', 'K.V.', 'Raitio'),
        ('K. Kare', 'K', 'Kare'),
        ('K. Kivivuori', 'K.', 'Kivivuori'),
        ('K. Piskonen', 'K.', 'Piskonen'),
        ('K. Villa', 'K.', 'Villa'),
        ('L.A. Hirvensalo', 'L.A.', 'Hirvensalo'),
        (r'''M-L. Vuorjoki''', 'M-L', 'Vuorjoki'),
        ('M. Irjanen', 'M.', 'Irjanen'),
        ('M. Rutanen', 'M.', 'Rutanen'),
        ('Matti K. Kallio', 'Matti K.', 'Kallio'),
        ('M.L. Reunanen', 'M.L.', 'Reunanen'),
        ('O.E. Juurikorpi', 'O.E.', 'Juurikorpi'),
        ('O.E. Tudeer', 'O.E.', 'Tudeer'),
        ('P. Kopperi', 'P.', 'Kopperi'),
        ('Pauli A. Kopperi', 'Pauli A.', 'Kopperi'),
        ('Pentti J. Huhtala', 'Pentti J.', 'Huhtala'),
        ('Pentti P. Heino', 'Pentti P.', 'Heino'),
        ('Pertti A. Palo', 'Pertti A.', 'Palo'),
        ('R. Sirokov', 'R.', 'Sirokov'),
        ('R.N.', 'R.', 'N.'),
        ('Raimo E. Tikkanen', 'Raimo E.', 'Tikkanen'),
        ('U. Ruhanen', 'U.', 'Ruhanen'),
        ('Unto E. Markkanen', 'Unto E.', 'Markkanen'),
        ('V. Vankkoja', 'V.', 'Vankkoja'),
        ('Väinö J. Tervaskari', 'Väinö J.', 'Tervaskari')
        ]

editors =\
        [
        ('E. Leikoski', 'E.', 'Leikoski')
        ]

missing_from_db =\
        [
        'Lynn Abbey',
        'Aleksandr Afanasjev',
        'Carl Ahlström',
        'Robert Aickman',
        'Alphonse Allais',
        'Andrew Allen',
        'Kingsley Amis',
        'Hans Christian Andersen',
        'Paul Dale Anderson',
        'Kevin J. Andersson',
        'Leonid Andrejev',
        'anonyymi',
        'Aleksei Apuhtin',
        'Robert Arthur',
        'Alice Askew',
        'Claude Askew',
        'Gerald Atkins',
        'A.A. Attanasio',
        'Scott Baker',
        'Louisa Baldwin',
        'William Baldwin',
        'Herman Bang',
        'Carolyn Banks',
        'Charles Beaumont',
        'A.C. Benson',
        'Michael Bishop',
        'Zealia Bishop',
        'Algernon Blackwood',
        'Michael Blumlein',
        'Elizabeth Bowen',
        'Marjorie Bowen',
        'Leigh Brackett',
        'Mary E. Braddon',
        'Gary Brandner',
        'Lilian Jackson Braun',
        'Joseph Payne Brennan',
        'Alan Brennert',
        'Ann Bridge',
        'Poppy Z. Brite',
        'D.K. Broster',
        'Edward Bryant',
        'John Buchan',
        'A.M. Burrage',
        'John L. Byrne',

        ]