translators =\
        [
        ('Aulis Rantasen työryhmä', 'Aulis Rantasen työryhmä', ''),
        ('Biokustannuksen käännösryhmä', 'Biokustannuksen käännösryhmä', ''),
        ('Turun yliopiston suomentajaseminaari', 'Turun yliopiston suomentajaseminaari', ''),
        ('A. Peromies', 'A.', 'Peromies'),
        ('A. Tiusanen', 'A.', 'Tiusanen'),
        ('Aarne A. Astala', 'Aarne A.', 'Astala'),
        ('Aarne T.K. Lahtinen', 'Aarne T.K.', 'Lahtinen'),
        ('A.M. Anttila', 'A.M.', 'Anttila'),
        ('E-L. Manner', 'E-L.', 'Manner'),
        ('E. Adrian', 'E.', 'Adrian'),
        ('E. Heikkinen', 'E.', 'Heikkinen'),
        ('E. Kivikkaho', 'E.', 'Kivikkaho'),
        ('E. Leikoski', 'E.', 'Leikoski'),
        ('H. Järvenpää', 'H.', 'Järvenpää'),
        ('E. Palsbo', 'E.', 'Palsbo'),
        ('H. Nuorpuu', 'H.', 'Nuorpuu'),
        ('H. Nurminen', 'H.', 'Nurminen'),
        ('Hugo L. Mäkinen', 'Hugo L.', 'Mäkinen'),
        ('I.K. Inha', 'I.K.', 'Inha'),
        ('J.K. Ihalainen', 'J.K.', 'Ihalainen'),
        ('J. Konkka', 'J.', 'Konkka'),
        ('J. Linturi', 'J.', 'Linturi'),
        ('J. K. Ihalainen', 'J. K.', 'Ihalainen'),
        ('J. Säilä', 'J.', 'Säilä (Judén)'),
        ('Jaakko V. Tapio', 'Jaakko V.', 'Tapio'),
        ('K.V. Raitio', 'K.V.', 'Raitio'),
        ('K. Kare', 'K', 'Kare'),
        ('K. Kivivuori', 'K.', 'Kivivuori'),
        ('K. Piskonen', 'K.', 'Piskonen'),
        ('K. Villa', 'K.', 'Villa'),
        ('L.A. Hirvensalo', 'L.A.', 'Hirvensalo'),
        (r'''M-L. Vuorjoki''', 'M-L', 'Vuorjoki'),
        ('M. Irjanen', 'M.', 'Irjanen'),
        ('M. Rutanen', 'M.', 'Rutanen'),
        ('Matti K. Kallio', 'Matti K.', 'Kallio'),
        ('M.L. Reunanen', 'M.L.', 'Reunanen'),
        ('M-L. Vuorjoki', 'M-L.', 'Vuorjoki'),
        ('O.E. Juurikorpi', 'O.E.', 'Juurikorpi'),
        ('O.E. Tudeer', 'O.E.', 'Tudeer'),
        ('P. Kopperi', 'P.', 'Kopperi'),
        ('Pauli A. Kopperi', 'Pauli A.', 'Kopperi'),
        ('Pentti J. Huhtala', 'Pentti J.', 'Huhtala'),
        ('Pentti P. Heino', 'Pentti P.', 'Heino'),
        ('Pertti A. Palo', 'Pertti A.', 'Palo'),
        ('R. Hakamies', 'R.', 'Hakamies'),
        ('R. Sirokov', 'R.', 'Sirokov'),
        ('R.N', 'R.', 'N.'),
        ('Raimo E. Tikkanen', 'Raimo E.', 'Tikkanen'),
        ('U. Ruhanen', 'U.', 'Ruhanen'),
        ('Unto E. Markkanen', 'Unto E.', 'Markkanen'),
        ('V. Tarkiainen', 'V.', 'Tarkiainen'),
        ('V. Vankkoja', 'Vankka', 'Vankkoja'),
        ('Vankka Vankkoja', 'Vankka', 'Vankkoja'),
        ('Väinö J. Tervaskari', 'Väinö J.', 'Tervaskari')
        ]

editors =\
        [
        ('E. Leikoski', 'E.', 'Leikoski')
        ]

missing_from_db =\
        [
        'Andrew Allen',
        'Kingsley Amis',
        'Paul Dale Anderson',
        'Kevin J. Andersson',
        'Scott Baker',
        'Carolyn Banks',
        'A.C. Benson',
        'Michael Bishop',
        'Zealia Bishop',
        'Joseph Payne Brennan',
        'John W. Campbell',
        'Leonard Cline',
        'Ken Cowley',
        'Bill Crider',
        'Jack Dann',
        'J. Wentworth Day',
        'Jack Dann',
        'David Drake',
        'Leah Bodine Drake',
        'Ronald Duncan',
        'Caroline Evans',
        'Sharon N. Faber',
        'Brad Ferguson',
        'Karen Joy Fowler',
        'Martin Gardner',
        'Melissa Mia Hall',
        'Nina Kiriki Hoffman',
        'Elizabeth Jane Howard',
        'Shirley Jackson',
        'Henry James',
        'M(ontague) R(hodes) James',
        'K.G. Johansson',
        'A.F. Kidd',
        'T.E.D. Klein',
        'L. Bradley Law',
        'D.H. Lawrence',
        'Margery Lawrence',
        'William M. Lee',
        'L.A. Lewis',
        'Robert H. Barlow',
        'George MacDonald',
        'K.C. Mann',
        'Bruce McAllister',
        'C.L. Moore',
        'Grant Morrison',
        'Oliver Onions',
        'Ralf Parland',
        'Seabury Quinn',
        'J.H. Riddell',
        'Jeffry Scott ',
        'Michael Shea',
        'Dyan Sheldon',
        'May Sinclair',
        'Dean Wesley Smith',
        'Lowell Kent Smith',
        'Sarah Smith',
        'Steve Rasnic Tem',
        'Hugh Walpole',
        'Erward Lucas White',
        'Lady Jane Wilde',
        'F. Paul Wilson',
        'Gahan Wilson',
        'Clement Wood',
        'Kai Aho',
        'Jari Ahonen',
        'Markus Ahonen',
        'Eija Elo',
        'Milka Hakkarainen',
        'Anne-Mari Halonen',
        'Jari Halonen',
        'Janne Harju',
        'Taru Hautala',
        'Pekka Hiltunen',
        'Kari Hintikka',
        'Timo Honkasalo',
        'Maiju Ihalainen',
        'Seppo Jokinen',
        'Yrjö Junttila',
        'Jarkko Juvonen',
        'Arvid Järnefelt',
        'Marko Järvinen',
        'Seppo Kallio',
        'Sirpa Kalliokoski',
        'Erkki Kanerva',
        'Jani Kangas',
        'Jenni Kauppinen',
        'Joonas Kinnunen',
        'Tommi Kinnunen',
        'Siria Kohonen',
        'Aino-Kaisa Koistinen',
        'Arto Koistinen',
        'Ville V. Kokko',
        'Kari Kontio',
        'Inkeri Kontro',
        'Petri Korhonen',
        'Unto Koskela',
        'Petri Kosonen',
        'Joni Kuusisto',
        'Tapio Lahtinen',
        'Tiina Laine',
        'Seppo Lappalainen',
        'Jade Lehtinen',
        'Jussi Lehtinen',
        'Vesa Lehtinen',
        'Alpo Leppänen',
        'Kari T. Leppänen',
        'Eeva Lindholm',
        'Heleena Lönnroth',
        'Pekka Manninen',
        'Sami Myllymäki',
        'Milla Mäenpää',
        'Merja Mäki',
        'Antti Niemelä',
        'Jussi K. Niemelä',
        'Kaj Niemi',
        'Teija Niemi',
        'Nina Niskanen',
        'Elisa Nurmi',
        'Marja Nykänen',
        'Liisa Näsi',
        'Asa Palo',
        'Sirpa Pasanen',
        'Niko Aslak Peltonen',
        'Tapio Peltonen',
        'Markku Penttilä',
        'Päivi Perttula',
        'Viktor Pettersson',
        'Aleksi Peura',
        'Jouni Pohjola',
        'Matias  Ranta',
        'Matilda  Ranta',
        'Mikko Rauhala',
        'Niina Räsänen',
        'Toni Saarinen',
        'Juha Salmi',
        'Juha Salminen',
        'Katja Salminen',
        'Anna Salonen',
        'Niko-Samuli Salonen',
        'Henna Sinisalo',
        'Miina Supinen',
        'Riku Talvitie',
        'Pihla Tammisto',
        'Ari Tervonen',
        'Lauri Timonen',
        'Jussi Tyni',
        'Claude Askew',
        'William Baldwin',
        'Marjorie Bowen',
        'Gardner Dozois',
        'W.W. Jacobs',
        'Roger Johnson',
        'Ronald Kelly',
        'Garry Kilworth',
        'Richard Middleton',
        'A. Merritt',
        'Ray Russell',
        'Shanghai North-China Herald (-lehdessä julkaistu)',
        'Lewis Shiner',
        'anonyymi',
        'Sara Heinämaa',
        'Venla Lintunen',
        'Ville Lintunen',
        'Vuokko Martikainen',
        'Sysi Mustonen',
        'Solina Riekkola',
        'Tuukka Tenhunen',
        'Alice Askew',
        'Louisa Baldwin',
        'Elizabeth Bowen',
        'Harvey Jacobs',
        'Robert Barbour Johnson',
        'James Patrick Kelly',
        'Haydn Middleton',
        'Eric Frank Russell',
        'San Francisco Examiner (-lehdessä julkaistu)',
        'Anna Heinämaa',
        'Kalle Lintunen',
        'Tiina Martikainen',
        'Sana Mustonen',
        'Joonas Riekkola',
        'Eeva-Liisa Tenhunen'
]
