publishers = [
    ('Absurdia', 'Absurdia', 'Absurdia'),
    ('Absurdia / Literis et Artibus Oy', 'Absurdia / Literis et Artibus Oy', 'Absurdia / Literis et Artibus Oy'),
    ('Acalla Oy', 'Acalla Oy', 'Acalla Oy'),
    ('Ahjo', 'Ahjo', 'Ahjo'),
    ('Aikakone ry', 'Aikakone', 'Aikakone Ry'),
    ('Ajanviete', 'Ajanviete', 'Ajanviete'),
    ('Ajatus Kirjat / Gummerus kustannus Oy', 'Ajatus Kirjat / Gummerus kustannus Oy', 'Ajatus Kirjat / Gummerus kustannus Oy'),
    ('Alea-Kirja', 'Alea-Kirja', 'Alea-Kirja'),
    ('Kustannus Oy Alfa', 'Alfa', 'Kustannus Oy Alfa'),
    ('Alligaattori Kustannus', 'Alligaattori Kustannus', 'Alligaattori Kustannus'),
    ('Andalusialainen [K|k]oira', 'Andalusialainen Koira', 'Andalusialainen Koira'),
    ('Anne Leinonen', 'Anne Leinonen', 'Anne Leinonen'),
    ('Aquarian Publications', 'Aquarian Publications', 'Aquarian Publications'),
    ('Art House( Oy)?', 'Art House', 'Art House Oy'),
    ('Atena( Kustannus Oy)?', 'Atena', 'Atena Kustannus Oy'),
    ('Aug. Kanervan kp.', 'Aug. Kanervan kp.', 'Aug. Kanervan kp.'),
    ('Aula & Co', 'Aula & Co', 'Aula & Co'),
    ('Aura', 'Aura', 'Aura'),
    ('Avain', 'Avain', 'Avain'),
    ('Avain / BTJ Finland Oy', 'Avain / BTJ Finland Oy', 'Avain / BTJ Finland Oy'),
    ('Aviador', 'Aviador', 'Aviador'),
    ('BTJ Finland Oy', 'BTJ Finland Oy', 'BTJ Finland Oy'),
    ('Basam Books( Oy)?', 'Basam Books', 'Basam Books Oy'),
    ('(Kustannus Oy )?Bazar( Kustannus)?( Oy)?', 'Bazar', 'Bazar Kustannus Oy'),
    ('Ben Roimola', 'Ben Roimola', 'Ben Roimola'),
    ('Biokustannus Oy', 'Biokustannus Oy', 'Biokustannus Oy'),
    ('Biokustannus Oy & Blavatsky-looshi ry. & Ruusu-Ristin Kirjallisuusseura ry. & Teosofis-kristosofinen kirjakauppa & Kustannusliike Aatma', 'Biokustannus Oy & Blavatsky-looshi ry. & Ruusu-Ristin Kirjallisuusseura ry. & Teosofis-kristosofinen kirjakauppa & Kustannusliike Aatma', 'Biokustannus Oy & Blavatsky-looshi ry. & Ruusu-Ristin Kirjallisuusseura ry. & Teosofis-kristosofinen kirjakauppa & Kustannusliike Aatma'),
    ('Book Studio( Oy)?( -kirjat)?', 'Book Studio', 'Book Studio Oy'),
    ('Books on Demand', 'Books on Demand', 'Books on Demand'),
    ('Cossus', 'Cossus', 'Cossus'),
    ('Desura', 'Desura', 'Desura'),
    ('Dream Catcher Oy', 'Dream Catcher', 'Dream Catcher Oy'),
    ('E. Viljanteen kirjakauppa ja kustannusliike', 'E. Viljanteen kirjakauppa ja kustannusliike', 'E. Viljanteen kirjakauppa ja kustannusliike'),
    ('E. Wilh. Michelsson', 'E. Wilh. Michelsson', 'E. Wilh. Michelsson'),
    ('E.O. Savolainen', 'E.O. Savolainen', 'E.O. Savolainen'),
    ('(Kustannusliike )?Edistys', 'Edistys', 'Kustannusliike Edistys'),
    ('Eero Erkon kustannuksella', 'Eero Erkon kustannuksella', 'Eero Erkon kustannuksella'),
    ('Egmont Kustannus Oy( Ab)?', 'Egmont Kustannus', 'Egmont Kustannus Oy Ab'),
    ('Egmont Kustannus Oy / Kirjalito', 'Egmont Kustannus / Kirjalito', 'Egmont Kustannus Oy / Kirjalito'),
    ('Emil Vainio', 'Emil Vainio', 'Emil Vainio'),
    ('Espoon science fiction- ja fantasiaseura( ESC ry)?', 'Espoon science fiction- ja fantasiaseura', 'Espoon science fiction- ja fantasiaseura ESC ry'),
    ('Etelä-Suomen kustannus Oy', 'Etelä-Suomen kustannus Oy', 'Etelä-Suomen kustannus Oy'),
    ('Ex Libris', 'Ex Libris', 'Ex Libris'),
    ('Fanzine Oy', 'Fanzine', 'Fanzine Oy'),
    ('Faros-kustannus( Oy)?', 'Faros-kustannus', 'Faros-kustannus Oy'),
    ('Finncon-yhdistys ry', 'Finncon-yhdistys ry', 'Finncon-yhdistys ry'),
    ('Finn Lectura', 'Finn Lectura', 'Finn Lectura'),
    ('Finnpublishers Oy', 'Finnpublishers', 'Finnpublishers Oy'),
    ('Flamongo Sanomat', 'Flamongo Sanomat', 'Flamongo Sanomat'),
    ('Florindan kirjakustantamo', 'Florindan kirjakustantamo', 'Florindan kirjakustantamo'),
    ('Kustannus Oy Forma', 'Forma', 'Kustannus Oy Forma'),
    ('Förlaget Harlequin AB', 'Förlaget Harlequin', 'Förlaget Harlequin AB'),
    ('G.E. Jansson ja K.', 'G.E. Jansson ja K.', 'G.E. Jansson ja K.'),
    ('G.L. Söderström', 'G.L. Söderström', 'G.L. Söderström'),
    ('G.W. Edlund', 'G.W. Edlund', 'G.W. Edlund'),
    ('Gaudeamus', 'Gaudeamus', 'Gaudeamus'),
    ('Gummerus Junior Oy', 'Gummerus Junior', 'Gummerus Junior Oy'),
    ('Gummerus\\s?[a-zA-Z\\ ]*\\s?(Oy)?', 'Gummerus', 'Gummerus Oy'),
    ('H. Nurhonen', 'H. Nurhonen', 'H. Nurhonen'),
    ('Kustannusosakeyhtiö HAI', 'HAI', 'Kustannusosakeyhtiö HAI'),
    ('Haamu', 'Haamu', 'Haamu'),
    ('Harlequin Enterprises( Ltd)?', 'Harlequin Enterprises', 'Harlequin Enterprises Ltd'),
    ('Hautakero Smial', 'Hautakero Smial', 'Hautakero Smial'),
    ('Kustannus Oy Helios', 'Helios', 'Kustannus Oy Helios'),
    ('Helsingin Science Fiction Seura ry', 'Helsingin Science Fiction Seura ry', 'Helsingin Science Fiction Seura ry'),
    ('Helsigin yliopiston science fiction klubi ry.', 'Helsigin yliopiston science fiction klubi ry.', 'Helsigin yliopiston science fiction klubi ry.'),
    ('Helsinki Media Oy', 'Helsinki Media', 'Helsinki Media Oy'),
    ('Helsinki Media Company Oy', 'Helsinki Media Company', 'Helsinki Media Company Oy'),
    ('Holger Schild', 'Holger Schild', 'Holger Schild'),
    ('Holger Schildt', 'Holger Schildt', 'Holger Schildt'),
    ('H. P. Lovecraft - Historiallinen seura ry', 'H. P. Lovecraft - Historiallinen seura ry', 'H. P. Lovecraft - Historiallinen seura ry'),
    ('Hurtan Biblios', 'Hurtan Biblios', 'Hurtan Biblios'),
    ('Idun', 'Idun', 'Idun'),
    ('Ihme Oy', 'Ihme', 'Ihme Oy'),
    ('Ilmarinen Oy', 'Ilmarinen', 'Ilmarinen Oy'),
    ('Intensive Ltd', 'Intensive', 'Intensive Ltd'),
    ('Into Kustannus( Oy)?', 'Into Kustannus', 'Into Kustannus Oy'),
    ('Isak Julin', 'Isak Julin', 'Isak Julin'),
    ('J. Simeliuksen perilliset', 'J. Simeliuksen perilliset', 'J. Simeliuksen perilliset'),
    ('J.W. Pihl', 'J.W. Pihl', 'J.W. Pihl'),
    ('(Kustannus )?(Oy )?Jalava', 'Jalava', 'Kustannus Oy Jalava'),
    ('Johanna Kirjakerho( Oy)?', 'Johanna Kirjakerho', 'Johanna Kirjakerho Oy'),
    ('John Books( Oy)?', 'John Books', 'John Books Oy'),
    ('Johnny Kniga( Publishing)?', 'Johnny Kniga', 'Johnny Kniga Publishing'),
    ('Jyrki Ijäs', 'Jyrki Ijäs', 'Jyrki Ijäs'),
    ('Kustannus Oy Jousi', 'Jousi', 'Kustannus Oy Jousi'),
    ('Jukka Rokka', 'Jukka Rokka', 'Jukka Rokka'),
    ('Jussi Vainikainen', 'Jussi Vainikainen', 'Jussi Vainikainen'),
    ('Jyväskylän Science Fiction Seura 42 ry', 'Jyväskylän Science Fiction Seura 42 ry', 'Jyväskylän Science Fiction Seura 42 ry'),
    ('K. E. Holm', 'K. E. Holm', 'K. E. Holm'),
    ('Kaarlo Halme', 'Kaarlo Halme', 'Kaarlo Halme'),
    ('Kallen kirjasto', 'Kallen kirjasto', 'Kallen kirjasto'),
    ('Kansa', 'Kansa', 'Kansa'),
    ('Kansan Raamattuseuran säätiö', 'Kansan Raamattuseuran säätiö', 'Kansan Raamattuseuran säätiö'),
    ('Kansan lehti', 'Kansan lehti', 'Kansan lehti'),
    ('Kansankirja', 'Kansankirja', 'Kansankirja'),
    ('Kansankulttuuri', 'Kansankulttuuri', 'Kansankulttuuri'),
    ('Kansanvalta', 'Kansanvalta', 'Kansanvalta'),
    ('Karas-sana Oy', 'Karas-sana', 'Karas-sana Oy'),
    ('Karatas-kirjat', 'Karatas-kirjat', 'Karatas-kirjat'),
    ('(Kustannus Oy Pieni )?Karhu', 'Karhu', 'Kustannus Oy Pieni Karhu'),
    ('Karisto( Oy)?', 'Karisto', 'Karisto Oy'),
    ('Karjalais-suomalaisen SNT:n valtion kustannusliike', 'Karjalais-suomalaisen SNT:n valtion kustannusliike', 'Karjalais-suomalaisen SNT:n valtion kustannusliike'),
    ('Karjalan ASNT:n Valtion [Kk]ustannusliike', 'Karjalan ASNT:n Valtion Kustannusliike', 'Karjalan ASNT:n Valtion Kkustannusliike'),
    ('Karjalan ASNT:n valtiollinen kustannusliike', 'Karjalan ASNT:n valtiollinen kustannusliike', 'Karjalan ASNT:n valtiollinen kustannusliike'),
    ('Kauppakirjapaino( Oy)?', 'Kauppakirjapaino', 'Kauppakirjapaino Oy'),
    ('Kauppiaitten [Kk]ustannus Oy', 'Kauppiaitten Kustannus', 'Kauppiaitten Kustannus Oy'),
    ('K. E. Holm', 'K. E. Holm', 'K. E. Holm'),
    ('(Oy )?Kirjalito( Ab)?', 'Kirjalito', 'Oy Kirjalito Ab'),
    ('Kirjaneliö', 'Kirjaneliö', 'Kirjaneliö'),
    ('Kirjapaja', 'Kirjapaja', 'Kirjapaja'),
    ('Kirjateos Oy', 'Kirjateos', 'Kirjateos Oy'),
    ('Kustannusosakeyhtiö Kirjava', 'Kirjava', 'Kustannusosakeyhtiö Kirjava'),
    ('Oy Kirjaviihde - Boknöje Ab', 'Kirjaviihde', 'Oy Kirjaviihde - Boknöje Ab'),
    ('Kirjavälitys', 'Kirjavälitys', 'Kirjavälitys'),
    ('Kirjayhtymä', 'Kirjayhtymä', 'Kirjayhtymä'),
    ('Kirjokansi', 'Kirjokansi', 'Kirjokansi'),
    ('Kivekäs', 'Kivekäs', 'Kivekäs'),
    ('Kustannus Oy Kivi', 'Kivi', 'Kustannus Oy Kivi'),
    ('Koivu ja Tähti Oy', 'Koivu ja Tähti', 'Koivu ja Tähti Oy'),
    ('Koko Kansan Kirjakerho', 'Koko Kansan Kirjakerho', 'Koko Kansan Kirjakerho'),
    ('Kolmio-kirjat', 'Kolmio-kirjat', 'Kolmio-kirjat'),
    ('Kolmiokirja( Oy)?', 'Kolmiokirja', 'Kolmiokirja Oy'),
    ('Kookos Kustannus', 'Kookos Kustannus', 'Kookos Kustannus'),
    ('Kuippana Kustannus Oy', 'Kuippana Kustannus', 'Kuippana Kustannus Oy'),
    ('Kulutusosuuskuntien keskusliitto', 'Kulutusosuuskuntien keskusliitto', 'Kulutusosuuskuntien keskusliitto'),
    ('Kuopion Science Fiction Seura', 'Kuopion Science Fiction Seura', 'Kuopion Science Fiction Seura'),
    ('Kuoriaiskirjat', 'Kuoriaiskirjat', 'Kuoriaiskirjat'),
    ('Kustannus Aarni', 'Kustannus Aarni', 'Kustannus Aarni'),
    ('Kustannus Hauenleuka', 'Kustannus Hauenleuka', 'Kustannus Hauenleuka'),
    ('Kustannus[\s\-]Mäkelä Oy', 'Kustannus-Mäkelä', 'Kustannus-Mäkelä Oy'),
    ('Kustannuskiila Oy', 'Kustannuskiila', 'Kustannuskiila Oy'),
    ('Kustannustalo', 'Kustannustalo', 'Kustannustalo'),
    ('Kustantamo Maatar', 'Kustantamo Maatar', 'Kustantamo Maatar'),
    ('Kuva ja [Ss]ana', 'Kuva ja sana', 'Kuva ja sana'),
    ('Kyläkirjaston Kuvalehti', 'Kyläkirjaston Kuvalehti', 'Kyläkirjaston Kuvalehti'),
    ('Kymppilehdet( Oy)?', 'Kymppilehdet', 'Kymppilehdet Oy'),
    ('Kääntöpiiri', 'Kääntöpiiri', 'Kääntöpiiri'),
    ('(Kustannus Oy )?(LIKE|Like)', 'LIKE', 'LIKE'),
    ('Laatusana Oy', 'Laatusana', 'Laatusana Oy'),
    ('Lahden Science Fiction Seura', 'Lahden Science Fiction Seura', 'Lahden Science Fiction Seura'),
    ('(Tähtitieteellinen Yhdistys )?Lapin Ursa', 'Lapin Ursa', 'Tähtitieteellinen Yhdistys Lapin Ursa'),
    ('Lasten [Kk]eskus', 'Lasten Keskus', 'Lasten Kkeskus'),
    ('Lehtimiehet Oy', 'Lehtimiehet', 'Lehtimiehet Oy'),
    ('Lehtipaino', 'Lehtipaino', 'Lehtipaino'),
    ('Lehtiyhtymä', 'Lehtiyhtymä', 'Lehtiyhtymä'),
    ('(Kustannus Oy )?Librum', 'Librum', 'Kustannus Oy Librum'),
    ('Lindstedtin antikvaarinen kirjakauppa', 'Lindstedtin antikvaarinen kirjakauppa', 'Lindstedtin antikvaarinen kirjakauppa'),
    ('Lindström & Co.', 'Lindström & Co.', 'Lindström & Co.'),
    ('Kustannus Oy Littera', 'Littera', 'Kustannus Oy Littera'),
    ('Loki-[Kk]irjat', 'Loki-Kirjat', 'Loki-Kirjat'),
    ('Love Kirjat', 'Love Kirjat', 'Love Kirjat'),
    ('Love-kustannus Oy', 'Love-kustannus', 'Love-kustannus Oy'),
    ('Luukkonen ja kumpp', 'Luukkonen ja kumpp', 'Luukkonen ja kumpp'),
    ('M. Vuolukka', 'M. Vuolukka', 'M. Vuolukka'),
    ('Mantere', 'Mantere', 'Mantere'),
    ('Marketiimi', 'Marketiimi', 'Marketiimi'),
    ('Mediapinta( Oy)?', 'Mediapinta', 'Mediapinta Oy'),
    ('Megadodo Publications Ltd', 'Megadodo Publications', 'Megadodo Publications Ltd'),
    ('Mestarikustannus', 'Mestarikustannus', 'Mestarikustannus'),
    ('Mikrokirjat', 'Mikrokirjat', 'Mikrokirjat'),
    ('Minerva', 'Minerva', 'Minerva'),
    ('Kustannusliike Mir', 'Mir', 'Kustannusliike Mir'),
    ('Kustannusosuuskunta Muusa', 'Muusa', 'Kustannusosuuskunta Muusa'),
    ('Myllylahti( Oy)?', 'Myllylahti', 'Myllylahti Oy'),
    ('Myrskykustannus( Ky)?', 'Myrskykustannus', 'Myrskykustannus Ky'),
    ('Mystica', 'Mystica', 'Mystica'),
    ('N.Y. Mills', 'N.Y. Mills', 'N.Y. Mills'),
    ('Nemo', 'Nemo', 'Nemo'),
    ('Nide Oy', 'Nide', 'Nide Oy'),
    ('Nordbooks', 'Nordbooks', 'Nordbooks'),
    ('Nostromo', 'Nostromo', 'Nostromo'),
    ('Nykylehdet( Oy)?', 'Nykylehdet', 'Nykylehdet Oy'),
    ('Nysalor-kustannus', 'Nysalor-kustannus', 'Nysalor-kustannus'),
    ('O. Andersin', 'Otto Andersin', 'Otto Andersin'),
    ('Kustannus Oy Odessa', 'Odessa', 'Kustannus Oy Odessa'),
    ('Omakustanne', 'Omakustanne', 'Omakustanne'),
    ('Orient Express', 'Orient Express', 'Orient Express'),
    ('Orienta', 'Orienta', 'Orienta'),
    ('Osuuskumma(-kustannus)?', 'Osuuskumma', 'Osuuskumma-kustannus'),
    ('Otava', 'Otava', 'Otava'),
    ('Otto Andersin', 'Otto Andersin', 'Otto Andersin'),
    ('Kustannusosakeyhtiö Paasilinna', 'Paasilinna', 'Kustannusosakeyhtiö Paasilinna'),
    ('Palander', 'Palander', 'Palander'),
    ('(Oy )?Paletti( Ab)?', 'Paletti', 'Oy Paletti Ab'),
    ('Pellervo(-[Ss]eura)?', 'Pellervo', 'Pellervo-Seura'),
    ('Kustannusosakeyhtiö Pikku-idis', 'Pikku-idis', 'Kustannusosakeyhtiö Pikku-idis'),
    ('Pilot-kustannus Oy', 'Pilot-kustannus', 'Pilot-kustannus Oy'),
    ('Piracy Press', 'Piracy Press', 'Piracy Press'),
    ('Pirkanmaan Kirjapaino ja Lehtikustannus', 'Pirkanmaan Kirjapaino ja Lehtikustannus', 'Pirkanmaan Kirjapaino ja Lehtikustannus'),
    ('Pohjalainen', 'Pohjalainen', 'Pohjalainen'),
    ('Pohjalaisen Kirjapaino', 'Pohjalaisen Kirjapaino', 'Pohjalaisen Kirjapaino'),
    ('Pohjoinen', 'Pohjoinen', 'Pohjoinen'),
    ('Pohjolan kustannus [Oo]y', 'Pohjolan kustannus', 'Pohjolan kustannus Oy'),
    ('Polaris - Oulun sf-seura', 'Polaris - Oulun sf-seura', 'Polaris - Oulun sf-seura'),
    ('Porvoon [Jj]ulmapaino', 'Porvoon Julmapaino', 'Porvoon Julmapaino'),
    ('Pro Games', 'Pro Games', 'Pro Games'),
    ('(Kustannusliike )?Progress', 'Progress', 'Kustannusliike Progress'),
    ('Päivä( Osakeyhtiö ja Fontana Media)?', 'Päivä Osakeyhtiö ja Fontana Media', 'Päivä Osakeyhtiö ja Fontana Media'),
    ('Päätalo-instituutti', 'Päätalo-instituutti', 'Päätalo-instituutti'),
    ('RKS-tietopalvelu Oy', 'RKS-tietopalvelu', 'RKS-tietopalvelu Oy'),
    ('RV-Kirjat', 'RV-Kirjat', 'RV-Kirjat'),
    ('Raivaajan kirjapaino', 'Raivaajan kirjapaino', 'Raivaajan kirjapaino'),
    ('Rakas-kustannus', 'Rakas-kustannus', 'Rakas-kustannus'),
    ('Reuna', 'Reuna', 'Reuna'),
    ('Ristin Voitto', 'Ristin Voitto', 'Ristin Voitto'),
    ('Kustannusliike Robustos', 'Robustos', 'Kustannusliike Robustos'),
    ('Robustos', 'Robustos', 'Robustos'),
    ('Ruotsista J. Simeliuksen perilliset', 'Ruotsista J. Simeliuksen perilliset', 'Ruotsista J. Simeliuksen perilliset'),
    ('SN-[Kk]irjat( Oy)?', 'SN-Kirjat', 'SN-Kirjat Oy'),
    ('Saksasta Työväenjärjestöjen tiedonantaja', 'Saksasta Työväenjärjestöjen tiedonantaja', 'Saksasta Työväenjärjestöjen tiedonantaja'),
    ('Salakirjat', 'Salakirjat', 'Salakirjat'),
    ('Kusta(n)?nusosakeyht(i)?ö Sammakko', 'Sammakko', 'Kustannusosakeyhtiö Sammakko'),
    ('(Kustannus- ja Kirjapaino Oy )?Sampo', 'Sampo', 'Kustannus- ja Kirjapaino Oy Sampo'),
    ('(Kustannusliike )?Sana', 'Sana', 'Kustannusliike Sana'),
    ('Sanasato', 'Sanasato', 'Sanasato'),
    ('Sanoma Magazines Finland( Oy)?', 'Sanoma Magazines Finland', 'Sanoma Magazines Finland Oy'),
    ('Sarjakustannus( Oy)?', 'Sarjakustannus', 'Sarjakustannus Oy'),
    ('Sarjamiehet', 'Sarjamiehet', 'Sarjamiehet'),
    ('Satakunnan kirjateollisuus( Oy)?', 'Satakunnan kirjateollisuus', 'Satakunnan kirjateollisuus Oy'),
    ('Satukustannus', 'Satukustannus', 'Satukustannus'),
    ('(Kustannusosakeyhtiö )?Savukeidas', 'Savukeidas', 'Kustannusosakeyhtiö Savukeidas'),
    ('Schildts & Söderströms', 'Schildts & Söderströms', 'Schildts & Söderströms'),
    ('Schildts Kustannus Oy', 'Schildts Kustannus', 'Schildts Kustannus Oy'),
    ('Seaflower Oy', 'Seaflower', 'Seaflower Oy'),
    ('Kustannus Oy Semic', 'Semic', 'Kustannus Oy Semic'),
    ('Semic', 'Semic', 'Semic'),
    ('Seonsana ry', 'Seonsana', 'Seonsana ry'),
    ('Sharda', 'Sharda', 'Sharda'),
    ('Siltala', 'Siltala', 'Siltala'),
    ('Sitruuna Kustannus Oy', 'Sitruuna Kustannus', 'Sitruuna Kustannus Oy'),
    ('Sley-kirjat', 'Sley-kirjat', 'Sley-kirjat'),
    ('Stabenfeldt AB', 'Stabenfeldt AB', 'Stabenfeldt AB'),
    ('Suom. sos. kustannusyhtiö', 'Suom. sos. kustannusyhtiö', 'Suom. sos. kustannusyhtiö'),
    ('Suomalainen puolue', 'Suomalainen puolue', 'Suomalainen puolue'),
    ('Suomalais-amerikkalainen kustannusyhtiö', 'Suomalais-amerikkalainen kustannusyhtiö', 'Suomalais-amerikkalainen kustannusyhtiö'),
    ('Suomalaisen Kirjallisuuden Seuran Kirjapaino', 'Suomalaisen Kirjallisuuden Seuran Kirjapaino', 'Suomalaisen Kirjallisuuden Seuran Kirjapaino'),
    ('Suomalaisen kansan romaanikirjasto', 'Suomalaisen kansan romaanikirjasto', 'Suomalaisen kansan romaanikirjasto'),
    ('Suomalaisen kirjallisuuden seura(n kp. Oy)?', 'Suomalaisen kirjallisuuden seura', 'Suomalaisen kirjallisuuden seuran kp. Oy'),
    ('Suomen Kirjallisuuden Seura', 'Suomen Kirjallisuuden Seura', 'Suomen Kirjallisuuden Seura'),
    ('Suomen Lähetysseura', 'Suomen Lähetysseura', 'Suomen Lähetysseura'),
    ('Suomen Sananjalka Oy', 'Suomen Sananjalka', 'Suomen Sananjalka Oy'),
    ('Suomen satamatyöntekijöiden kustannusosuuskunta', 'Suomen satamatyöntekijöiden kustannusosuuskunta', 'Suomen satamatyöntekijöiden kustannusosuuskunta'),
    ('Suomen tieteis- ja fantasiakirjoittajat ry', 'Suomen tieteis- ja fantasiakirjoittajat ry', 'Suomen tieteis- ja fantasiakirjoittajat ry'),
    ('Suomen tieteiskirjoittajat ry ja Turun yliopiston tieteiskulttuurikabinetti', 'Suomen tieteiskirjoittajat ry ja Turun yliopiston tieteiskulttuurikabinetti', 'Suomen tieteiskirjoittajat ry ja Turun yliopiston tieteiskulttuurikabinetti'),
    ('Suomen Tolkien-seura Kontu ry', 'Suomen Tolkien-seura Kontu ry', 'Suomen Tolkien-seura Kontu ry'),
    ('Suomi', 'Suomi', 'Suomi'),
    ('Suuri [Ss]uomalainen [Kk]irjakerho( Oy)?', 'Suuri Suomalainen Kirjakerho', 'Suuri Suomalainen Kirjakerho Oy'),
    ('Suuri lukukirjasto', 'Suuri lukukirjasto', 'Suuri lukukirjasto'),
    ('Säilä Luukkonen ja kumpp', 'Säilä Luukkonen ja kumpp', 'Säilä Luukkonen ja kumpp'),
    ('TK-kustannus( Oy)?', 'TK-kustannus', 'TK-kustannus Oy'),
    ('(Kustannus Oy )?Taifuuni', 'Taifuuni', 'Kustannus Oy Taifuuni'),
    ('Taikajousi', 'Taikajousi', 'Taikajousi'),
    ('Tajo', 'Tajo', 'Tajo'),
    ('Tajunta Media', 'Tajunta Media', 'Tajunta Media'),
    ('Tammi', 'Tammi', 'Tammi'),
    ('Tampereen Science [Ff]iction Seura( ry)?', 'Tampereen Science Fiction Seura ry', 'Tampereen Science Ffiction Seura ry'),
    ('Tampereen [Ss]entraalikirjapaino( Oy)?', 'Tampereen Sentraalikirjapaino', 'Tampereen Ssentraalikirjapaino Oy'),
    ('Taru', 'Taru', 'Taru'),
    ('Tekijä', 'Tekijä', 'Tekijä'),
    ('Tekijän kustantama', 'Tekijän kustantama', 'Tekijän kustantama'),
    ('(Kustannusosakeyhtiö )?Teos', 'Teos', 'Kustannusosakeyhtiö Teos'),
    ('Teosofinen kirjakauppa ja kustannusliike', 'Teosofinen kirjakauppa ja kustannusliike', 'Teosofinen kirjakauppa ja kustannusliike'),
    ('Terra Cognita', 'Terra Cognita', 'Terra Cognita'),
    ('Texthouse', 'Texthouse', 'Texthouse'),
    ('The Crime Corporation', 'The Crime Corporation', 'The Crime Corporation'),
    ('The Tree Club', 'The Tree Club', 'The Tree Club'),
    ('Tieteiskulttuuriyhdistys', 'Tieteiskulttuuriyhdistys', 'Tieteiskulttuuriyhdistys'),
    ('Tieto-tila Oy', 'Tieto-tila', 'Tieto-tila Oy'),
    ('Kustannusosakeyhtiö Tietäjä', 'Tietäjä', 'Kustannusosakeyhtiö Tietäjä'),
    ('Torni kustantamo', 'Torni kustantamo', 'Torni kustantamo'),
    ('Turbator', 'Turbator', 'Turbator'),
    ('Turbator/Pelipeitto Oy( kustannus)?', 'Turbator/Pelipeitto', 'Turbator/Pelipeitto Oy kustannus'),
    ('Tuomas Saloranta', 'Tuomas Saloranta', 'Tuomas Saloranta'),
    ('Tuomas Saloranta ja Venla Lintunen', 'Tuomas Saloranta ja Venla Lintunen', 'Tuomas Saloranta ja Venla Lintunen'),
    ('Turun Kirjapaino- ja Sanomalehti Oy', 'Turun Kirjapaino- ja Sanomalehti', 'Turun Kirjapaino- ja Sanomalehti Oy'),
    ('Turun Science Fiction Seura ry', 'Turun Science Fiction Seura ry', 'Turun Science Fiction Seura ry'),
    ('Turun yliopiston tieteiskulttuurikabinetti ry', 'Turun yliopiston tieteiskulttuurikabinetti ry', 'Turun yliopiston tieteiskulttuurikabinetti ry'),
    ('Osakeyhtiö Työ', 'Työ', 'Osakeyhtiö Työ'),
    ('Työkansan kirjapaino', 'Työkansan kirjapaino', 'Työkansan kirjapaino'),
    ('Työmiehen kustannusyhtiö', 'Työmiehen kustannusyhtiö', 'Työmiehen kustannusyhtiö'),
    ('Työväen Sivistysliitto', 'Työväen Sivistysliitto', 'Työväen Sivistysliitto'),
    ('Työväen kirjallisuuden edistämisyhdistys', 'Työväen kirjallisuuden edistämisyhdistys', 'Työväen kirjallisuuden edistämisyhdistys'),
    ('Työväen kustannus Oy', 'Työväen kustannus', 'Työväen kustannus Oy'),
    ('Työväen sanomalehti [Oo]y', 'Työväen sanomalehti', 'Työväen sanomalehti Ooy'),
    ('Työväenjärjestöjen tiedonantaja', 'Työväenjärjestöjen tiedonantaja', 'Työväenjärjestöjen tiedonantaja'),
    ('Tähtiallianssi - Suomen tähtien sota -seura', 'Tähtiallianssi - Suomen tähtien sota -seura', 'Tähtiallianssi - Suomen tähtien sota -seura'),
    ('Unto Mononen yhdistys ry', 'Unto Mononen yhdistys ry', 'Unto Mononen yhdistys ry'),
    ('Uoti &amp; Grönroos', 'Uoti &amp; Grönroos', 'Uoti &amp; Grönroos'),
    ('Urheilijain kustannus Oy', 'Urheilijain kustannus', 'Urheilijain kustannus Oy'),
    ('Ursa', 'Ursa', 'Ursa'),
    ('Uusi Kirjakerho( Oy)?', 'Uusi Kirjakerho', 'Uusi Kirjakerho Oy'),
    ('Uusi tie', 'Uusi tie', 'Uusi tie'),
    ('Uusrahvaanoimainen spekulatiivinen fiktio', 'Uusrahvaanoimainen spekulatiivinen fiktio', 'Uusrahvaanoimainen spekulatiivinen fiktio'),
    ('VV-Kustannus', 'VV-Kustannus', 'VV-Kustannus'),
    ('Vaasa( Oy)?', 'Vaasa', 'Vaasa Oy'),
    ('Oy Valistus', 'Valistus', 'Oy Valistus'),
    ('Valistus', 'Valistus', 'Valistus'),
    ('Valitut Palat', 'Valitut Palat', 'Valitut Palat'),
    ('Kirjapaino-Oy Valo', 'Valo', 'Kirjapaino-Oy Valo'),
    ('Valpas-Mainos', 'Valpas-Mainos', 'Valpas-Mainos'),
    ('Valtion kustannusliike( kirja)?', 'Valtion kustannusliike', 'Valtion kustannusliike kirja'),
    ('Kustannus Oy Vasara', 'Vasara', 'Kustannus Oy Vasara'),
    ('Vaskikirjat', 'Vaskikirjat', 'Vaskikirjat'),
    ('Versum', 'Versum', 'Versum'),
    ('Vieraskielisen kirjallisuuden kustannusliike', 'Vieraskielisen kirjallisuuden kustannusliike', 'Vieraskielisen kirjallisuuden kustannusliike'),
    ('Vihtori Kosonen', 'Vihtori Kosonen', 'Vihtori Kosonen'),
    ('Viihdekirjat', 'Viihdekirjat', 'Viihdekirjat'),
    ('Vii(h)?(d)?eviikarit( Oy)?', 'Viihdeviikarit', 'Viihdeviikarit Oy'),
    ('Viikkosanomat Oy', 'Viikkosanomat', 'Viikkosanomat Oy'),
    ('Viipurin Suomalaisen Kirjallisuuden Seura', 'Viipurin Suomalaisen Kirjallisuuden Seura', 'Viipurin Suomalaisen Kirjallisuuden Seura'),
    ('Vuorjoki', 'Vuorjoki', 'Vuorjoki'),
    ('Väinö Andelin', 'Väinö Andelin', 'Väinö Andelin'),
    ('W. Churberg', 'W. Churberg', 'W. Churberg'),
    ('WSOY', 'WSOY', 'WSOY'),
    ('Waasan painoyhtiö', 'Waasan painoyhtiö', 'Waasan painoyhtiö'),
    ('Wanhain Herrain Huone', 'Wanhain Herrain Huone', 'Wanhain Herrain Huone'),
    ('Weilin & Göös', 'Weilin & Göös', 'Weilin & Göös'),
    ('Weilin &amp; Göös', 'Weilin & Göös', 'Weilin & Göös'),
    (r'Weilin\+Göös', 'Weilin & Göös', 'Weilin & Göös'),
    ('Welkin [Bb]ooks', 'Welkin Books', 'Welkin Bbooks'),
    ('Wennerbergs Förlag', 'Wennerbergs Förlag', 'Wennerbergs Förlag'),
    ('Wilén', 'Vilén', 'Wilén'),
    ('Winthers Forlag', 'Winthers Forlag', 'Winthers Forlag'),
    ('Yliopistopaino', 'Yliopistopaino', 'Yliopistopaino'),
    ('Zum Teufel Kustannus', 'Zum Teufel', 'Zum Teufel Kustannus'),
    ('(Oy )?(Suomen )?[Kk]irja', 'Kirja', 'Kustannus Oy  Kirja'),
    ('Kustannus [Oo]y Kirja', 'Kirja', 'Kustannus Oy Kirja')]

