pubseries = [
    ('10 mk:n romaaneja( -sarja)?', '10 mk:n romaaneja'),
    ('10 mk:n romaani -sarja', '10 mk:n romaani -sarja'),
    ('10 mkan nuorisosarja', '10 mkan nuorisosarja'),
    ('10 mk:n sarja', '10 mk:n sarja'),
    ('50 p(enni|:)n kirjasto', '50 pennin kirjasto'),
    ('A-sarja', 'A-sarja'),
    ('Aavetaajuus-kirjat', 'Aavetaajuus-kirjat'),
    ('Aavetaajuus-klassikot', 'Aavetaajuus-klassikot'),
    ('Action-sarja', 'Action-sarja'),
    ('Ahjon ajanvietelukemisto', 'Ahjon ajanvietelukemisto'),
    ('Agentti-sarja', 'Agentti-sarja'),
    ('Aikamme kertojat -sarja', 'Aikamme kertojat -sarja'),
    ('Aikamme kertojia( -sarja)?', 'Aikamme kertojat -sarja'),
    ('Alexandre Dumas[i\']n historialliset romaanit',
     'Alexandre Dumasin historialliset romaanit'),
    ('Amerikka-sarja', 'Amerikka-sarja'),
    ('Andersinin 2 mk. kirjasarja', 'Andersinin 2 mk. kirjasarja'),
    ('Arena-kirja', 'Arena-kirja'),
    ('Arena-sarja', 'Arena-sarja'),
    ('Atschi!-pokkari', 'Atschi!-pokkari'),
    ('Basam Books klassikko( -sarja)?', 'Basam Books klassikko -sarja'),
    ('Basam Shakti -sarja', 'Basam Shakti -sarja'),
    ('Best Books -sarja', 'Best Books -sarja'),
    ('Best [Ss]eller( -sarja)?', 'Best Seller'),
    ('Bon-sarja', 'Bon'),
    ('Book Studio -kirjat', 'Book Studio -kirjat'),
    ('Collector [Aa]ntologia', 'Collector Antologia'),
    ('Delfiinikirjat', 'Delfiinikirjat'),
    ('Elävä maailmankirjallisuus', 'Elävä maailmankirjallisuus'),
    ('Englantilaisia romaaneja', 'Englantilaisia romaaneja'),
    ('Eurooppa-sarja', 'Eurooppa-sarja'),
    ('FAN-sarja', 'FAN-sarja'),
    ('FBH-kirjat', 'FBH-kirjat'),
    ('Fantasiasarja', 'Fantasiasarja'),
    ('Fantasy-sarja', 'Fantasy-sarja'),
    ('Galax-sarja', 'Galax-sarja'),
    ('(Galaxy|GALAXY)(\s)?[Ss]cifi( )?(-sarja)?', 'GALAXY Scifi'),
    ('GALAXY( )?-sarja', 'GALAXY Scifi'),
    ('GIRL:IT-sarja', 'GIRL:IT-sarja'),
    ('Gummeruksen [Nn]uorten [Kk]irjasto', 'Gummeruksen Nuorten Kirjasto'),
    ('Gummeruksen nuortenkirjoja', 'Gummeruksen nuortenkirjoja'),
    ('H.P. Lovecraftin kootut teokset', 'H.P. Lovecraftin kootut teokset'),
    ('Hai-kirja', 'Hai-kirja'),
    ('Hard Core -sarja', 'Hard Core -sarja'),
    ('Helmi-sarja', 'Helmi-sarja'),
    ('Helppohintainen kotikirjasto', 'Helppohintainen kotikirjasto'),
    ('Helppohintainen novelli- ja romaanijakso',
     'Helppohintainen novelli- ja romaanijakso'),
    ('Helsingin Kaiun kertomuskokoelma', 'Helsingin Kaiun kertomuskokoelma'),
    ('Historialliset romaanit', 'Historialliset romaanit'),
    ('Horisontti-sarja', 'Horisontti-sarja'),
    ('Horror-sarja', 'Horror-sarja'),
    ('Hyvää ajanvietettä( -sarja)?', 'Hyvää ajanvietettä -sarja'),
    ('Hämärän rajoilla -sarja', 'Hämärän rajoilla -sarja'),
    ('Into pokkari', 'Into pokkari'),
    ('Isot keltaiset -sarja', 'Isot keltaiset -sarja'),
    ('Jalavan Fantasiasarja', 'Jalavan Fantasiasarja'),
    ('Jalavan SciFi-sarja', 'Jalavan SciFi-sarja'),
    ('Jalavan [Kk]auhusarja', 'Jalavan kauhusarja'),
    ('Jatkolukemisto', 'Jatkolukemisto'),
    ('Jep-sarja', 'Jep-sarja'),
    ('Joka kodin tähtikirjasto', 'Joka kodin tähtikirjasto'),
    ('Joutoaikoina', 'Joutoaikoina'),
    ('Joutohetkinä', 'Joutohetkinä'),
    ('Junior Scifi', 'Junior Scifi'),
    ('Jättipokkarit', 'Jättipokkarit'),
    ('Kansanvallan näytelmistö', 'Kansanvallan näytelmistö'),
    ('Neuvostokirjallisuutta-sarja', 'Neuvostokirjallisuutta-sarja'),
    ('Kariston 10 mk:n romaaneja', 'Kariston 10 mk:n romaaneja'),
    ('Kariston 50 pennin romaaneja', 'Kariston 50 pennin romaaneja'),
    ('Kariston klassi(lli)?nen kirjasto', 'Kariston klassillinen kirjasto'),
    ('Kariston nuoriso(n)?(\s)?kirjoja', 'Kariston nuorisonkirjoja'),
    ('Kariston nuortenkirjasto', 'Kariston nuortenkirjasto'),
    ('Karis(t)?on nuortenkirjoja', 'Kariston nuortenkirjoja'),
    ('Kariston(n)? romaanisarja', 'Kariston romaanisarja'),
    ('Kauhujuttu-sarja', 'Kauhujuttu-sarja'),
    ('Kauhukabinetti-sarja', 'Kauhukabinetti-sarja'),
    ('Kauhusarja', 'Kauhusarja'),
    ('Kauhutarinoita', 'Kauhutarinoita'),
    ('Keijut-sarja', 'Keijut-sarja'),
    ('Keltainen kirjasto', 'Keltainen kirjasto'),
    ('Keltainen pokkari', 'Keltainen pokkari'),
    ('Keltanokka-sarja', 'Keltanokka-sarja'),
    ('Keskiyön kirjasto( -sarja)?', 'Keskiyön kirjasto'),
    ('Kirjakerho lasten kirjapaketti', 'Kirjakerho lasten kirjapaketti'),
    ('Kirjallinen löytöretki', 'Kirjallinen löytöretki'),
    ('Kirjallisuutta kouluille', 'Kirjallisuutta kouluille'),
    ('Kirjan "parhaita nuorisokirjoja"', 'Kirjan "parhaita nuorisokirjoja"'),
    ('Kirjayhtymän science fiction -sarja', 'Kirjayhtymän science fiction -sarja'),
    ('Klassikko-sarja', 'Klassikko-sarja'),
    ('Kolibri-kirjasto', 'Kolibri-kirjasto'),
    ('Kolmen tähden sarja', 'Kolmen tähden sarja'),
    ('Kolmio-kirja', 'Kolmio-kirja'),
    ('Kompassikirja', 'Kompassikirja'),
    ('Kontakti-sarja', 'Kontakti-sarja'),
    ('Kotien suurromaanit( -sarja)?', 'Kotien suurromaanit'),
    ('Kotikirjaston klassikoita', 'Kotikirjaston klassikoita'),
    ('Koululaiset kirjoittavat koululaisille',
     'Koululaiset kirjoittavat koululaisille'),
    ('Koululaiskirjasto', 'Koululaiskirjasto'),
    ('Koulun peruskirjasto', 'Koulun peruskirjasto'),
    ('Krimi-sarja', 'Krimi-sarja'),
    ('Kristallin lapset', 'Kristallin lapset'),
    ('Kuoriaiskirjat-sarja', 'Kuoriaiskirjat'),
    ('Kultaiset klassikot( -sarja)?', 'Kultaiset klassikot'),
    ('Kultapokkari', 'Kultapokkari'),
    ('Kuoriaisvihkot', 'Kuoriaisvihkot'),
    ('Kuukauden Action -sarja', 'Kuukauden Action -sarja'),
    ('Kyläkirjaston kuvalehti B-sarjan kirjoina',
     'Kyläkirjaston kuvalehti B-sarjan kirjoina'),
    ('Kymmenen markan romaaneja', 'Kymmenen markan romaaneja'),
    ('Kyöpeli-sarja', 'Kyöpeli-sarja'),
    ('Laatukirjat', 'Laatukirjat-sarja'),
    ('Laatukirjat-sarja', 'Laatukirjat-sarja'),
    ('LIKE(-)?fantasia', 'LIKE fantasia'),
    ('Lasten oma kirjasto', 'Lasten oma kirjasto'),
    ('Lasten toivekirjasto', 'Lasten toivekirjasto'),
    ('Leija-sarja', 'Leija-sarja'),
    ('(Like|LIKE) [Ss]ci[Ff]i( -sarja)?', 'LIKE Scifi'),
    ('Like fantasia -sarja', 'LIKE fantasia'),
    ('Like kauhu -sarja', 'LIKE kauhu'),
    ('Like-Scifi-sarja', 'LIKE Scifi'),
    ('Like-pokkari', 'Like-pokkari'),
    ('Loki-Kirjojen sf-sarja', 'Loki-Kirjojen sf-sarja'),
    ('Love kirjat -sarja', 'Love kirjat -sarja'),
    ('Lovecraftilaisia kertomuksia', 'Lovecraftilaisia kertomuksia'),
    ('Lukemisen pikkujättiläiset -sarja', 'Lukemisen pikkujättiläiset -sarja'),
    ('Lukupalat-sarja', 'Lukupalat-sarja'),
    ('Lukurengas(-sarja)?', 'Lukurenga'),
    ('M-[Kk]irjat-sarja', 'M-kirjat-sarja'),
    ('M-sarja', 'M-kirjat-sarja'),
    ('M-novellit( scifi)?(-sarja)?', 'M-novellit scifi-sarja'),
    ('Maailman [Pp]arhaat [Kk]ertojat -sarja',
     'Maailman Parhaat Kertojat -sarja'),
    ('Maailman parhaita nuorisonkirjoja', 'Maailman parhaita nuorisonkirjoja'),
    ('Mailta ja meriltä( -sarja)?', 'Mailta ja meriltä -sarja'),
    ('Mantereen nuorisokirjasto', 'Mantereen nuorisokirjasto'),
    ('Meidän lasten kirjasto', 'Meidän lasten kirjasto'),
    ('Merkkiteoksia maailman kirjallisuudesta',
     'Merkkiteoksia maailman kirjallisuudesta'),
    ('Mikrosarja', 'Mikrosarja'),
    ('Minerva-pokkarit', 'Minerva-pokkarit'),
    ('Minerva klassikot', 'Minerva klassikot'),
    ('Minipokkari-sarja.', 'Minipokkari-sarja.'),
    ('Moderneja kirjailijoita -sarja', 'Moderneja kirjailijoita -sarja'),
    ('Musta virta -scifi', 'Musta virta -scifi'),
    ('Mysteeri-sarja', 'Mysteeri-sarja'),
    ('Neuvostokirjallisuutta-sarja', 'Neuvostokirjallisuutta-sarja'),
    ('Neuvostonovelleja-sarja', 'Neuvostonovelleja-sarja'),
    ('Nobel-sarja', 'Nobel-sarja'),
    ('Nocturne-sarja', 'Nocturne-sarja'),
    ('Nuorten 10 mk:n sarja', 'Nuorten 10 mk:n sarja'),
    ('Nuorten kirjaseura', 'Nuorten kirjaseura'),
    ('Nuorten kirjasto', 'Nuorten kirjasto'),
    ('Nuorten kirjoja', 'Nuorten kirjoja'),
    ('Nuorten minipokkarit', 'Nuorten minipokkarit'),
    ('Nuorten novellisto -sarja', 'Nuorten novellisto -sarja'),
    ('Nuorten parhaat -sarja', 'Nuorten parhaat -sarja'),
    ('Nuorten sarja', 'Nuorten sarja'),
    ('Nuorten toivekirjasto', 'Nuorten toivekirjasto'),
    ('Nykyromaaneja', 'Nykyromaaneja'),
    ('Näkökulma', 'Näkökulma'),
    ('O.K.-sarja', 'O.K.-sarja'),
    ('Omnibus-sarja', 'Omnibus-sarja'),
    ('Otavan 50 p(enni)?(:)?n kirjasto', 'Otavan 50 pennin kirjasto'),
    ('Otavan fantasiaromaani( -sarja)?', 'Otavan fantasiaromaani'),
    ('Otavan kirjasto -sarja', 'Otavan kirjasto -sarja'),
    ('Otavan klassikot', 'Otavan klassikot'),
    ('(ON )?(\()?Otavan nuortenkirjoja(\))?( )?(-sarja)?',
     'Otavan nuortenkirjoja -sarja'),
    ('Otavan romaanisarja', 'Otavan romaanisarja'),
    ('Otavan uusi romaanisarja', 'Otavan uusi romaanisarja'),
    ('Otavan( )?kirjasto', 'Otavan kirjasto'),
    ('Paletin Salama-sarja', 'Paletin Salama-sarja'),
    ('Paletin nuoriso(kirja)? -sarja', 'Paletin nuoriso -sarja'),
    ('Parhaita nuorison kirjoja -sarja', 'Parhaita nuorison kirjoja -sarja'),
    ('Penny girl -sarja', 'Penny girl -sarja'),
    ('Perettin seikkailusarja', 'Perettin seikkailusarja'),
    ('Perry Rhodan, Miehemme maailmankaikkeudessa',
     'Perry Rhodan, Miehemme maailmankaikkeudessa'),
    ('Pieni kirjasto', 'Pieni kirjasto'),
    ('Poikain jännityskirjasto', 'Poikain jännityskirjasto'),
    ('Poikien kirjasto', 'Poikien kirjasto'),
    ('Poikien sarja', 'Poikien sarja'),
    ('Poikien seikkailukirjasto', 'Poikien seikkailukirjasto'),
    ('Poikien sininen sarja', 'Poikien sininen sarja'),
    ('Pokkaristo(-sarja)?', 'Pokkaristo-sarja'),
    ('Pollux-hevoskerho( )?-sarja', 'Pollux-hevoskerho -sarja'),
    ('Pääskysen kirjasto', 'Pääskysen kirjasto'),
    ('Nuorten kirjoja, uusi sarja', 'Nuorten kirjoja, uusi sarja'),
    ('Portti kirjat', 'Portti-kirjat'),
    ('Portti(-)?kirjat', 'Portti-kirjat'),
    ('Pultti-sarja', 'Pultti-sarja'),
    ('Raketti-sarja', 'Raketti-sarja'),
    ('Riksin sarja', 'Riksin sarja'),
    ('Ruotsalaisia tieteistarinoita', 'Ruotsalaisia tieteistarinoita'),
    ('Ruusu-Risti-Kirjasto', 'Ruusu-Risti-Kirjasto'),
    ('SAPO-sarja', 'SAPO-sarja'),
    ('Sapo', 'SAPO-sarja'),
    ('Satujen ja tarujen maailma -sarja', 'Satujen ja tarujen maailma -sarja'),
    ('Satupirtti', 'Satupirtti'),
    ('Saturnus SciFi -sarja', 'Saturnus SciFi -sarja'),
    ('Savukeitaan kauhuklassikot', 'Savukeitaan kauhuklassikot'),
    ('Savukeitaan maailman nykyrunouden sarja',
     'Savukeitaan maailman nykyrunouden sarja'),
    ('Sci-fi\s+-sarja', 'Sci-fi -sarja'),
    ('SciFi-sarja', 'Jalavan SciFi-sarja'),
    ('Science Fiction -sarja', 'Science Fiction -sarja'),
    ('Scifin parhaita -sarja', 'Scifin parhaita -sarja'),
    ('Seaflowerin Classics -sarja', 'Seaflowerin Classics -sarja'),
    ('Seaflower\'s Classics -sarja', 'Seaflowerin Classics -sarja'),
    ('Seikkailu-sarja', 'Seikkailu-sarja'),
    ('Seikkailujen maailma( -sarja)?', 'Seikkailujen maailma -sarja'),
    ('Seikkailukirjasto', 'Seikkailukirjasto'),
    ('Seikkailuromaaneja', 'Seikkailuromaaneja'),
    ('Seikkailusarja', 'Seikkailusarja'),
    ('Seitsentähde[nt]-sarja', 'Seitsentähdet-sarja'),
    ('Seuranäytelmiä', 'Seuranäytelmiä'),
    ('Shokki', 'Shokki'),
    ('Shokki-sarja', 'Shokki-sarja'),
    ('Shokki-sarja', 'Shokki-sarja'),
    ('Silmukka( )?-sarja', 'Silmukka-sarja'),
    ('Siniset Taskukirjasto', 'Siniset Taskukirjasto'),
    ('Siniset-sarja', 'Siniset-sarja'),
    ('Sirius-sarja', 'Sirius-sarja'),
    ('Soundi-kirjat', 'Soundi-kirjat'),
    ('Suomalaisen kirjallisuuden klassikoita -sarja',
     'Suomalaisen kirjallisuuden klassikoita -sarja'),
    ('Suomalaisia aavenovelleja', 'Suomalaisia aavenovelleja'),
    ('Suomalaisia aikamatkanovelleja', 'Suomalaisia aikamatkanovelleja'),
    ('Suomalaisia lohikäärmetarinoita', 'Suomalaisia lohikäärmetarinoita'),
    ('Suomen dekkariseuran julkaisusarja', 'Suomen dekkariseuran julkaisusarja'),
    ('Suomen kansan kirjakerhon romaaneja', 'Suomen kansan kirjakerhon romaaneja'),
    ('Suomalaisen kirjallisuuden klassikoita',
     'Suomalaisen kirjallisuuden klassikoita'),
    ('Suomen lasten kirjoja', 'Suomen lasten kirjoja'),
    ('Suuri [Nn]uorten [Kk]irjakerho -sarja',
     'Suuri Nuorten Kirjakerho -sarja'),
    ('Suurten kertojain teoksia', 'Suurten kertojain teoksia'),
    ('Taistelija-sarja', 'Taistelija-sarja'),
    ('Tam [Tt]am -kirja(t)?', 'Tam Tam -kirjat'),
    ('Tam tam -sarja', 'Tam Tam -kirjat'),
    ('Tammen klassikkopokkarit', 'Tammen klassikkopokkarit'),
    ('Tammen nuortenkirjat -sarja', 'Tammen nuortenkirjat -sarja'),
    ('Tammen nuortenpokkarit', 'Tammen nuortenpokkarit'),
    ('Taskukirjasto(-sarja)?', 'Taskukirjasto'),
    ('Taskutieto', 'Taskutieto'),
    ('Taskutoveri', 'Taskutoveri'),
    ('Tieteisromaani-sarja', 'Tieteisromaani-sarja'),
    ('Tieteissarja', 'Tieteissarja'),
    ('Tiikeri-sarja', 'Tiikeri-sarja'),
    ('Top books -sarja', 'Top books -sarja'),
    ('Trendi-klassikot -sarja', 'Trendi-klassikot -sarja'),
    ('Tuhansille kodeille tuhatjärvien maassa',
     'Tuhansille kodeille tuhatjärvien maassa'),
    ('Työväen kirjarengas', 'Työväen kirjarengas'),
    ('Tähtisarja', 'Tähtisarja'),
    ('Ursan sf-sarja', 'Ursan sf-sarja'),
    ('Uusia [Rr]omaaneja', 'Uusia Romaaneja'),
    ('Vaasan nuorisokirjat', 'Vaasan nuorisokirjat'),
    ('Valikoima kummituskertomuksia', 'Valikoima kummituskertomuksia'),
    ('Valiokirjasto', 'Valiokirjasto'),
    ('Valittuja tieteiskertomuksia', 'Valittuja tieteiskertomuksia'),
    ('Valitut', 'Valitut'),
    ('Vaskikirjojen sf-kirjat', 'Vaskikirjojen sf-kirjat'),
    ('Verne-sarja', 'Verne-sarja'),
    ('Viiden markan romaaneja', 'Viiden markan romaaneja'),
    ('Viiden markan sarja', 'Viiden markan sarja'),
    ('Voittaja-sarja', 'Voittaja-sarja'),
    ('Välipalaksi', 'Välipalaksi'),
    ('W.S.O.Y:N näytelmäsarja n:o', 'W.S.O.Y:N näytelmäsarja n:o'),
    ('W.S.O.Y:n koululaiskirjasto', 'W.S.O.Y:n koululaiskirjasto'),
    ('WSOY[\s-][Pp]okkari( -sarja)?', 'WSOY Pokkari'),
    ('Weilin\+Göösin [Kk]irjasto', 'Weilin+Göösin Kirjasto'),
    ('Weilin\+Göösin kirjasto', 'Weilin+Göösin Kirjasto'),
    ('m-novellit scifi -sarja', 'm-novellit scifi -sarja'),
    ('Loisto(-sarja)?', 'Loisto'),
    ('Seven( -sarja)?', 'Seven')]

important_pubseries = (
    'FAN-sarja',
    'Fantasy-sarja',
    'FBH-kirjat',
    'GALAXY Scifi',
    'Jalavan SciFi-sarja',
    'LIKE Scifi',
    'Loki-Kirjojen sf-sarja',
    'Musta virta -scifi',
    'Portti-kirjat',
    'Saturnus SciFi-sarja',
    'Science Fiction -sarja',
    'Sci-fi -sarja',
    'Scifin parhaita -sarja',
    'Tieteisromaani-sarja',
    'Tieteissarja',
    'Ursan sf-sarja',
    'Vaskikirjojen sf-kirjat'
)

bookseries = [
    ('5. aalto, osa', '5. aalto'),
    ('A. Conan Doylen kootut kertomukset', 'A. Conan Doylen kootut kertomukset'),
    ('A. Conan Doylen kootut teokset', 'A. Conan Doylen kootut teokset'),
    ('Aalto ja Myrsky', 'Aalto ja Myrsky'),
    ('Aavehevoset', 'Aavehevoset'),
    ('Aavekaksoset-sarja', 'Aavekaksoset-sarja'),
    ('Abadazad', 'Abadazad'),
    ('Abarat', 'Abarat'),
    ('Across the Universe', 'Across the Universe'),
    ('Aigi-saaga', 'Aigi-saaga'),
    ('Aijalin saaren tarut', 'Aijalin saaren tarut'),
    ('Aikavartio', 'Aikavartio'),
    ('Ajan Pyörä(n)?\s?(?P<ext>johdanto-osa)?', 'Ajan Pyörä'),
    ('Ajan verkko', 'Ajan verkko'),
    ('Alismaan tarinat', 'Alismaan tarinat'),
    ('Alvinin (?P<num2>.+) kirja', 'Alvinin kirja'),
    ('Amberin kronikat', 'Amberin kronikat'),
    ('Amerikan kuninkaalliset', 'Amerikan kuninkaalliset'),
    ('Ami-kirjat', 'Ami-kirjat'),
    ('Animorphs(: Megamorphs)?', 'Animorphs'),
    ('Apollon', 'Apollon'),
    ('Artemis Fowl', 'Artemis Fowl'),
    ('Atlanthaksen kronikka', 'Atlanthaksen kronikka'),
    ('Aurora', 'Aurora'),
    ('Avaruuden arvoitukset', 'Avaruuden arvoitukset'),
    ('Avaimenkantaja', 'Avaimenkantaja'),
    ('Baabel', 'Baabel'),
    ('Bartimeus-trilogia', 'Bartimeus-trilogia'),
    ('Belgarionin ja Mallorean tarujen vanhat käsikirjoitukset',
       'Belgarionin ja Mallorean tarujen vanhat käsikirjoitukset'),
    ('Belgarionin taru', 'Belgarionin taru'),
    ('Bird Box', 'Bird Box'),
    ('Bob Moran -sarja', 'Bob Moran -sarja'),
    ('Buster Bayliss', 'Buster Bayliss'),
    ('Calli Chase', 'Calli Chase'),
    ('Canopus Argossa( )?(-sarja)', 'Canopus Argossa -sarja'),
    ('Caraval', 'Caraval'),
    ('Cathy', 'Cathy'),
    ('Cavallonin kronikat', 'Cavallonin kronikat'),
    ('Charmed - Siskoni on noita -sarja', 'Charmed - Siskoni on noita -sarja'),
    ('Chrestomancin maailmat', 'Chrestomancin maailmat'),
    ('Danny Dunn\s?-sarja', 'Danny Dunn -sarja'),
    (r'David & Larissa', 'David & Larissa'),
    ('Delirium-trilogia', 'Delirium-trilogia'),
    ('Deltoran vyö', 'Deltoran vyö'),
    ('Demonisodat-sarja', 'Demonisodat-sarja'),
    ('Deptfordin hiirten seikkailuja', 'Deptfordin hiirten seikkailuja'),
    ('Deverryn taru', 'Deverryn taru'),
    ('Doctor Who', 'Doctor Who'),
    ('Dorsai-trilogia', 'Dorsai-trilogia'),
    ('DragonLance, Viides aika', 'DragonLance, Viides aika'),
    ('DragonLance-sarja', 'DragonLance-sarja'),
    ('DragonLance - Kadonneet historiat', 'DragonLance - Kadonneet historiat'),
    ('DragonLance - Kuolemanportti', 'DragonLance - Kuolemanportti'),
    ('DragonLance - Minotaurisodat', 'DragonLance - Minotaurisodat'),
    ('DragonLance kronikat', 'DragonLance kronikat'),
    ('DragonLance legendat', 'DragonLance legendat'),
    ('DragonLance-sarja, Dhamon-saaga', 'DragonLance-sarja, Dhamon-saaga'),
    ('Dragonlance Saga -sarja', 'Dragonlance Saga -sarja'),
    ('Dramoja', 'Dramoja'),
    ('Drenain tarut', 'Drenain tarut'),
    ('Eeden-trilogia', 'Eeden-trilogia'),
    ('Eeppisten epäonnistumisten sarja', 'Eeppisten epäonnistumisten sarja'),
    ('Elben taru', 'Elben taru'),
    ('Eleniumin taru', 'Eleniumin taru'),
    ('Eliittisotilaat', 'Eliittisotilaat'),
    ('Ella Aura', 'Ella Aura'),
    ('Ella', 'Ella'),
    ('Elminster-saaga', 'Elminster-saaga'),
    ('Eloonjääneet-sarja', 'Eloonjääneet-sarja'),
    ('Emily the Strange', 'Emily the Strange'),
    ('Endgame', 'Endgame'),
    ('Engelsfors-trilogia', 'Engelsfors-trilogia'),
    ('Enkeliakatemia', 'Enkeliakatemia'),
    ('Ensimmäinen laki: osa', 'Ensimmäinen laki'),
    ('Ensimmäisen kuninkaan saaga,Etsijät', 'Ensimmäisen kuninkaan saaga'),
    ('Ensimmäisen kuninkaan saaga', 'Ensimmäisen kuninkaan saaga'),
    ('Eteläraja-trilogia', 'Eteläraja-trilogia'),
    ('Etsijät', 'Etsijät'),
    ('Eve Dallas( )?(-sarja)?', 'Eve Dallas -sarja'),
    ('Everlife', 'Everlife'),
    ('Everworld', 'Everworld'),
    ('Faunoidit', 'Faunoidit'),
    ('O\'Dwyerin serkut', 'O\'Dwyerin serkut'),
    ('Fionavarin kuvakudos', 'Fionavarin kuvakudos'),
    ('Flash Gordon( -sarja)?', 'Flash Gordon'),
    ('Forgotten Realms. Drowin tytär', 'Forgotten Realms. Drowin tytär'),
    ('Forgotten Realms. Drowprinsessa-sarja',
     'Forgotten Realms. Drowprinsessa-sarja'),
    ('Forgotten Realms. Kuninkaita ja neuvonantajia',
     'Forgotten Realms. Kuninkaita ja neuvonantajia'),
    ('Forgotten Realms. Laulut ja miekat', 'Forgotten Realms. Laulut ja miekat'),
    ('Gaealian tarustoa', 'Gaealian tarustoa'),
    ('The Ghost Network', 'The Ghost Network'),
    ('Gigi ja Henry', 'Gigi ja Henry'),
    ('Gokahdan saagat', 'Gokahdan saagat'),
    ('Goosebumps Kauhumaa', 'Goosebumps Kauhumaa'),
    ('Goosebumps', 'Goosebumps'),
    ('Grishaversumi', 'Grishaversumi'),
    ('Haaksirikkoiset', 'Haaksirikkoiset'),
    ('Haavekaupunki', 'Haavekaupunki'),
    ('Half Bad', 'Half Bad'),
    ('Halla-sarja', 'Halla-sarja'),
    ('Halloweentown', 'Halloweentown'),
    ('Harper Connelly -sarja', 'Harper Connelly -sarja'),
    ('Helliconia-trilogia', 'Helliconia-trilogia'),
    ('Helppohintainen kirjasto', 'Helppohintainen kirjasto'),
    ('Harry Potter', 'Harry Potter'),
    ('Herkules', 'Herkules'),
    ('Hermux Tantamoqin seikkailuja', 'Hermux Tantamoqin seikkailuja'),
    ('Hirunda', 'Hirunda'),
    ('Hirviötrilogia', 'Hirviötrilogia'),
    ('Hopea-sarja', 'Hopea-sarja'),
    ('Houkutus', 'Houkutus'),
    ('Hukkuneiden laakso', 'Hukkuneiden laakso'),
    ('Hurjien tarinoiden talo', 'Hurjien tarinoiden talo'),
    ('Idhunin kronikat', 'Idhunin kronikat'),
    ('Ihan mieletön juttu', 'Ihan mieletön juttu'),
    ('Ihmemaa Oz', 'Ihmemaa Oz'),
    ('Iik!', 'Iik!'),
    ('Ikikesä(, osa)?', 'Ikikesä'),
    ('Ikimaa', 'Ikimaa'),
    ('Illuminatus!', 'Illuminatus!'),
    ('Ilmastokvartetti', 'Ilmastokvartetti'),
    ('Ilmestyneiden taru', 'Ilmestyneiden taru'),
    ('Intertwined', 'Intertwined'),
    ('Iron Sky', 'Iron Sky'),
    ('Isadella', 'Isadella'),
    ('Iso-Werneri-sarja', 'Iso-Werneri-sarja'),
    ('Jaan-sarja', 'Jaan'),
    ('Jack Sparrow', 'Jack Sparrow'),
    ('Jenny Dean -sarja', 'Jenny Dean -sarja'),
    ('Jep-sarja', 'Jep-sarja'),
    ('Jules Vernen romaanit', 'Jules Vernen romaanit'),
    ('Jääkansan tarina', 'Jääkansan tarina'),
    ('Jäämaan kronikka', 'Jäämaan kronikka'),
    ('Jäätuulen laakso -trilogia osa', 'Jäätuulen laakso -trilogia'),
    ('Kaaoksen aika', 'Kaaoksen aika'),
    ('Kaaoksen sota', 'Kaaoksen sota'),
    ('Kadonneet [Hh]istoriat', 'Kadonneet historiat'),
    ('Kadonneet kronikat osa', 'Kadonneet kronikat'),
    ('Kadonnut laivasto', 'Kadonnut laivasto'),
    ('Kaikkeuden kirja', 'Kaikkeuden kirja'),
    ('Kaikkeuden kivi', 'Kaikkeuden kivi'),
    ('Kaksosauringot', 'Kaksosauringot'),
    ('Kalle-Kustaa Korkin seikkailuja', 'Kalle-Kustaa Korkin seikkailuja'),
    ('Kalmanväreitä-sarja', 'Kalmanväreitä-sarja'),
    ('Kanen aikakirjat', 'Kanen aikakirjat'),
    ('Kangin rykmentti', 'Kangin rykmentti'),
    ('Kapinaenkelit', 'Kapinaenkelit'),
    ('Katrionan tarina', 'Katrionan tarina'),
    ('Kauhuagentti Nelli Rapp', 'Kauhuagentti Nelli Rapp'),
    ('Kauhukartano', 'Kauhukartano'),
    ('Kehä', 'Kehä'),
    ('Keihäänkantajan taru', 'Keihäänkantajan taru'),
    ('Keplo Leutokalma', 'Keplo Leutokalma'),
    ('Keskilinnan ritarit', 'Keskilinnan ritarit'),
    ('Kevätuhrit', 'Kevätuhrit'),
    ('Kirja aikojen alusta', 'Kirja aikojen alusta'),
    ('Kirjanoita', 'Kirjanoita'),
    ('Kissojen kesken', 'Kissojen kesken'),
    ('Kivistänäkijät osa', 'Kivistänäkijät osa'),
    ('Konetrilogia', 'Konetrilogia'),
    ('Kontakti-kirja', 'Kontakti-kirja'),
    ('Korpinkehät', 'Korpinkehät'),
    ('Korpinlaulu', 'Korpinlaulu'),
    ('Korppi-sarja', 'Korppi-sarja'),
    ('Korppikartanon salat', 'Korppikartanon salat'),
    ('Kostaja - ([a-zäöå]+) kirja', 'Kostaja -kirja'),
    ('Kostaja-sarja', 'Kostaja'),
    ('Kotka-sarja', 'Kotka-sarja'),
    ('Kraa-trilogia', 'Kraa-trilogia'),
    ('Kuikansulka-trilogia', 'Kuikansulka-trilogia'),
    ('Kultasiipien keijukoulu', 'Kultasiipien keijukoulu'),
    ('Kulttuuri-sarja', 'Kulttuuri'),
    ('Kummakylä', 'Kummakylä'),
    ('Kumppanusten kirja', 'Kumppanusten kirja'),
    ('Kuninkaansurmaajan kronikka: ([a-zA-ZåäöÅÄÖ]+ päivä)',
     'Kuninkaansurmaajan kronikka'),
    ('Kuolemanportti', 'Kuolemanportti'),
    ('Kuolemattoman Nicholas Flamelin salaisuudet',
     'Kuolemattoman Nicholas Flamelin salaisuudet'),
    ('Kuolemattomat', 'Kuolemattomat'),
    ('Kuparisaari', 'Kuparisaari'),
    ('Kurki-sarja', 'Kurki-sarja'),
    ('Kurki-kirja', 'Kurki-sarja'),
    ('Kuuden piiri', 'Kuuden piiri'),
    ('Kuura-trilogia', 'Kuura-trilogia'),
    ('Kvanttipainovoima', 'Kvanttipainovoima'),
    ('Kvanttivaras', 'Kvanttivaras'),
    ('Kätkijät', 'Kätkijät'),
    ('Kävelevät koneet', 'Kävelevät koneet'),
    ('Käärmesodan taru', 'Käärmesodan taru'),
    ('Lampun lapset', 'Lampun lapset'),
    ('Langenneet enkelit', 'Langenneet enkelit'),
    ('Langennut enkeli', 'Langennut enkeli'),
    ('Lankhmar osa', 'Lankhmar osa'),
    ('Lasilapset', 'Lasilapset'),
    ('Leiloman tarinat', 'Leiloman tarinat'),
    ('Lierolan kronikka osa', 'Lierolan kronikka'),
    ('Liekkevän trilogia', 'Liekkevän trilogia'),
    ('Liekki-trilogia', 'Liekki-trilogia'),
    ('Lohikäärmeakatemia', 'Lohikäärmeakatemia'),
    ('Lohikäärmelaakso', 'Lohikäärmelaakso'),
    ('Lohikäärmelaivat', 'Lohikäärmelaivat'),
    ('Lohikäärmeratsastaja', 'Lohikäärmeratsastaja'),
    ('Lohikäärmesydän', 'Lohikäärmesydän'),
    ('Loihtijakronikka', 'Loihtijakronikka'),
    ('Lordi Kultainen', 'Lordi Kultainen'),
    ('Louhi-sarja', 'Louhi-sarja'),
    ('Loukkupoika', 'Loukkupoika'),
    ('Lujaveriset', 'Lujaveriset'),
    ('Lumen ja jään maa', 'Lumen ja jään maa'),
    ('Lumoleipomo', 'Lumoleipomo'),
    ('Lumotun metsän kronikat', 'Lumotun metsän kronikat'),
    ('Lyran kirjat', 'Lyran kirjat'),
    ('Maailmanjako', 'Maailmanjako'),
    ('Maailmanrumpu', 'Maailmanrumpu'),
    ('Maailman viimeiset tyypit', 'Maailman viimeiset tyypit'),
    ('Maameren tarinat', 'Maameren tarinat'),
    ('Maan lapset -sarja', 'Maan lapset -sarja'),
    ('Maan, veden ja tulen väki', 'Maan, veden ja tulen väki'),
    ('MaddAddam-trilogia', 'MaddAddam-trilogia'),
    ('Magiaa', 'Magiaa'),
    ('Magisterium', 'Magisterium'),
    ('Magnus Chase', 'Magnus Chase'),
    ('Mahtavat', 'Mahtavat'),
    ('Malamanteri', 'Malamanteri'),
    ('Mallorean taru', 'Mallorean taru'),
    ('Manaajan matka', 'Manaajan matka'),
    ('Manalan valtiaat', 'Manalan valtiaat'),
    ('Marie Corellin romaanit', 'Marie Corellin romaanit'),
    ('Mars-kirjat', 'Mars-kirjat'),
    ('Matka Asgårdiin', 'Matka Asgårdiin'),
    ('Matkakirjallisuutta-sarja', 'Matkakirjallisuutta-sarja'),
    ('Matkantekijä', 'Matkantekijä'),
    ('Maze Runner', 'Maze Runner'),
    ('Megamorphs', 'Megamorphs'),
    ('Meritytöt', 'Meritytöt'),
    ('Merlinin kronikat', 'Merlinin kronikat'),
    ('Mersumies-trilogia', 'Mersumies-trilogia'),
    ('Metro', 'Metro'),
    ('Metsän kansa', 'Metsän kansa'),
    ('Metsästäjän miekat', 'Metsästäjän miekat'),
    ('Mifonki-sarja', 'Mifonki-sarja'),
    ('Monster High', 'Monster High'),
    ('Monsterijengi', 'Monsterijengi'),
    ('Mortina', 'Mortina'),
    ('Muinainen pimeys', 'Muinainen pimeys'),
    ('Muistoja planeetta Maasta', 'Muistoja planeetta Maasta'),
    ('Multiversumin palautus', 'Multiversumin palautus'),
    ('Murroskaudet', 'Murroskaudet'),
    ('Musta Haltia -trilogia osa', 'Musta Haltia -trilogia'),
    ('Musta kaista( -sarja)?', 'Musta kaista'),
    ('Musta komppania', 'Musta komppania'),
    ('Musta torni', 'Musta torni'),
    ('Mustamiekka', 'Mustamiekka'),
    ('Mustan tikarin perintö', 'Mustan tikarin perintö'),
    ('Mustan tikarin veljeskunta', 'Mustan tikarin veljeskunta'),
    ('Mustien ruusujen maa', 'Mustien ruusujen maa'),
    ('Myrsky-sarja', 'Myrsky'),
    ('Myrskynvartija', 'Myrskynvartija'),
    ('Mystic City', 'Mystic City'),
    ('Myyttihovi', 'Myyttihovi'),
    ('Narnia-sarja', 'Narnia-sarja'),
    ('Narri ja Näkijä', 'Narri ja Näkijä'),
    ('Nelimaan tarinat', 'Nelimaan tarinat'),
    ('Neljäs piiri', 'Neljäs piiri'),
    ('Neonkaupunki', 'Neonkaupunki'),
    ('Nevermoor', 'Nevermoor'),
    ('North End', 'North End'),
    ('Nicholas North', 'Nicholas North'),
    ('Nick Carter', 'Nick Carter'),
    ('Noitakronikat', 'Noitakronikat'),
    ('Noitamestari', 'Noitamestari'),
    ('Noitametsä-trilogia', 'Noitametsä-trilogia'),
    ('Noitien taistelu', 'Noitien taistelu'),
    ('Noituri', 'Noituri'),
    ('Nymfit', 'Nymfit'),
    ('Näkijän kirja', 'Näkijän kirja'),
    ('Näki[hj]än taru', 'Näkijän taru'),
    ('Näkymätön piiri', 'Näkymätön piiri'),
    ('Nälkäpeli', 'Nälkäpeli'),
    ('Ohdakemaa', 'Ohdakemaa'),
    ('Olentojen planeetta', 'Olentojen planeetta'),
    ('Olympoksen sankarit', 'Olympoksen sankarit'),
    ('Oman keisarien aikakirjat', 'Oman keisarien aikakirjat'),
    ('Onttujen ([a-zåäöA-ZÅÄÖ]+ kirja)', 'Onttujen kirja'),
    ('Orïshan perintö', 'Orïshan perintö'),
    ('Orrin', 'Orrin'),
    ('Oswald Bastable', 'Oswald Bastable'),
    ('Otorin klaanin tarina', 'Otorin klaanin tarina'),
    ('Outolintu', 'Outolintu'),
    ('Painajaisia ja unikuvia', 'Painajaisia ja unikuvia'),
    ('Paljaan taivaan alla', 'Paljaan taivaan alla'),
    ('Palkkasoturit [I]+ kirja', 'Palkkasoturit'),
    ('Pappiskvintetti - osa', 'Pappiskvintetti'),
    ('Paranormaali', 'Paranormaali'),
    ('Partholon', 'Partholon'),
    ('Pax', 'Pax'),
    ('Pedon sydän', 'Pedon sydän'),
    ('Pekka Lipponen ja Kalle-Kustaa Korkki',
     'Pekka Lipponen ja Kalle-Kustaa Korkki'),
    ('Pekka Lipposen seikkailuja', 'Pekka Lipposen seikkailuja'),
    ('Pellucidar', 'Pellucidar'),
    ('Pendergast-sarja', 'Pendergast-sarja'),
    ('Percy Jackson', 'Percy Jackson'),
    ('Perillinen', 'Perillinen'),
    ('Pernin lohikäärmeritarit', 'Pernin lohikäärmeritarit'),
    ('Perry Rhodan: Miehemme maailmankaikkeudessa',
     'Perry Rhodan: Miehemme maailmankaikkeudessa'),
    ('Pet Agents', 'Pet Agents'),
    ('Petoveto 5', 'Petoveto 5'),
    ('Pimeyden ihmeet', 'Pimeyden ihmeet'),
    ('Pimeyden oppilas osa', 'Pimeyden oppilas'),
    ('Pimeyden polut -sarja', 'Pimeyden polut -sarja'),
    ('Pimeä nousee', 'Pimeä nousee'),
    ('Pirates of the Caribbean', 'Pirates of the Caribbean'),
    ('Pirre', 'Pirre'),
    ('Pitkä Maa', 'Pitkä Maa'),
    ('Pohjankontu', 'Pohjankontu'),
    ('Pohjoisen legendat', 'Pohjoisen legendat'),
    ('Pohjoiset ennustukset', 'Pohjoiset ennustukset'),
    ('Pohjoistuuli', 'Pohjoistuuli'),
    ('Pohjola-sarja', 'Pohjola-sarja'),
    ('Poseidonin lapset', 'Poseidonin lapset'),
    ('Prinsessa & Pahikset', 'Prinsessa & Pahikset'),
    ('Profeetan ruusu( osa)?', 'Profeetan ruusu'),
    ('Pronssikronikat', 'Pronssikronikat'),
    ('Pronssisoturit', 'Pronssisoturit'),
    ('Prydainin kronikka', 'Prydainin kronikka'),
    ('Punainen sulka -sarja', 'Punainen sulka -sarja'),
    ('Punaisen luostarin kronikoita', 'Punaisen luostarin kronikoita'),
    ('Pyhimys-sarja', 'Pyhimys-sarja'),
    ('Qyamian kirjat', 'Qyamian kirjat'),
    ('R.A. Salvatoren Lukkikuningattaren sota(, osa)?',
     'R.A. Salvatoren Lukkikuningattaren sota'),
    ('Rakkaus ei katso aikaa', 'Rakkaus ei katso aikaa'),
    ('Ransom-trilogia', 'Ransom-trilogia'),
    ('Rauta-saaga', 'Rauta-saaga'),
    ('Red Caps -sarja', 'Red Caps -sarja'),
    ('Redwallin taru', 'Redwallin taru'),
    ('Remnants - Selviytyjät Maasta', 'Remnants - Selviytyjät Maasta'),
    ('Replica', 'Replica'),
    ('Replica, Geeni-trilogia', 'Replica, Geeni-trilogia'),
    ('Revontulitalli-sarja', 'Revontulitalli-sarja'),
    ('Rikkaiden unelmat', 'Rikkaiden unelmat'),
    ('Rising Moon', 'Rising Moon'),
    ('Robotit', 'Robotit'),
    ('Roistoakatemia', 'Roistoakatemia'),
    ('Roswell High', 'Roswell High'),
    ('Routala', 'Routala'),
    ('Routasisarukset', 'Routasisarukset'),
    ('Royaumen aikakirjat', 'Royaumen aikakirjat'),
    ('Qwarru-sarja', 'Qwarru-sarja'),
    ('Saarimaan saaga', 'Saarimaan saaga'),
    ('Salaiset kansiot - [Tt]he X-Files -sarja',
     'Salaiset kansiot - The X-Files -sarja'),
    ('Sammon vartijat', 'Sammon vartijat'),
    ('Savuvarkaat', 'Savuvarkaat'),
    ('Satumaa-sarja', 'Satumaa'),
    ('Scott Saunders -sarja', 'Scott Saunders -sarja'),
    ('Selviytyjät', 'Selviytyjät'),
    ('Sensored Reality', 'Sensored Reality'),
    ('Septimus Heap', 'Septimus Heap'),
    ('Sexton Blake( -sarja)?', 'Sexton Blake -sarja'),
    ('Shamaanilegendat', 'Shamaanilegendat'),
    ('Shannaran jälkeläiset', 'Shannaran jälkeläiset'),
    ('Shannaran perintö', 'Shannaran perintö'),
    ('Sielujen sota', 'Sielujen sota'),
    ('Sielunratsastajat', 'Sielunratsastajat'),
    ('Sihis', 'Sihis'),
    ('Siilon saaga', 'Siilon saaga'),
    ('Siskoni vampyyri', 'Siskoni vampyyri'),
    ('Solamnian nousu', 'Solamnian nousu'),
    ('Sonja', 'Sonja'),
    ('Sookie Stackhouse', 'Sookie Stackhouse'),
    ('Soturikissat-novellit', 'Soturikissat-novellit'),
    ('Soturikissat erikoisseikkailu', 'Soturikissat erikoisseikkailu'),
    ('Soturikissat, Kolmikon mahti', 'Soturikissat, Kolmikon mahti'),
    ('Soturikissat, Tähtien enne', 'Soturikissat, Tähtien enne'),
    ('Soturikissat, Uusi profetia', 'Soturikissat, Uusi profetia'),
    ('Soturikissat', 'Soturikissat'),
    ('Spiderwickin kronikat', 'Spiderwickin kronikat'),
    ('Spiraalipuutarha-sarja', 'Spiraalipuutarha-sarja'),
    ('Star Wars - Jedioppilas', 'Star Wars - Jedioppilas'),
    ('Star Wars - Jeditehtävä', 'Star Wars - Jeditehtävä'),
    ('Star Wars -klassikot', 'Star Wars -klassikot'),
    ('Star Wars( )?-sarja', 'Star Wars -sarja'),
    ('Star Wars', 'Star Wars'),
    ('Stravaganza', 'Stravaganza'),
    ('Sudenhetket', 'Sudenhetket'),
    ('Sukelluslabradori Tufunus tutkii', 'Sukelluslabradori Tufunus tutkii'),
    ('Suoja', 'Suoja'),
    ('Suojelijoiden tähti( osa)?', 'Suojelijoiden tähti'),
    ('Suolan valtakunta', 'Suolan valtakunta'),
    ('Suomea lohikäärmeille', 'Suomea lohikäärmeille'),
    ('Susiraja', 'Susiraja'),
    ('Synkät vedet', 'Synkät vedet'),
    ('Synnit', 'Synnit'),
    ('Sysimetsän kronikat', 'Sysimetsän kronikat'),
    ('Syysmaa', 'Syysmaa'),
    ('Särkynyt meri', 'Särkynyt meri'),
    ('Säätiö', 'Säätiö'),
    ('Taikajengi', 'Taikajengi'),
    ('Taikakoirat', 'Taikakoirat'),
    ('Taikavaras', 'Taikavaras'),
    ('Taikuri ja taskuvaras', 'Taikuri ja taskuvaras'),
    ('Taikuuden aika', 'Taikuuden aika'),
    ('Taistelupeli-sarja', 'Taistelupeli-sarja'),
    ('Takeshitan kintereillä', 'Takeshitan kintereillä'),
    ('Talismans of Thunder', 'Talismans of Thunder'),
    ('Talon-saaga', 'Talon-saaga'),
    ('Tamulin taru', 'Tamulin taru'),
    ('Tarinoita Alagaësiasta', 'Tarinoita Alagaësiasta'),
    ('Tarinoita Maan reunalta', 'Tarinoita Maan reunalta'),
    ('Taru kolmesta miekasta', 'Taru kolmesta miekasta'),
    ('Taru [Ss]ilmäterästä', 'Taru silmäterästä'),
    ('Tarzan-kirjat', 'Tarzan-kirjat'),
    ('Tauno Karilaan valitut seikkailukertomukset',
     'Tauno Karilaan valitut seikkailukertomukset'),
    ('Taynikma', 'Taynikma'),
    ('The Body Jumper', 'The Body Jumper'),
    ('The Nightmare Room( -trilogia)?', 'The Nightmare Room -trilogia'),
    ('The Walking Dead', 'The Walking Dead'),
    ('The Young World', 'The Young World'),
    ('Themis-kansioiden ([a-zäöå}]+) kirja', 'Themis-kansiot'),
    ('Throne of Glass', 'Throne of Glass'),
    ('Tiger Team', 'Tiger Team'),
    ('Time Riders', 'Time Riders'),
    ('tl-kerho-sarja', 'tl-kerho-sarja'),
    ('Toinen todellisuus', 'Toinen todellisuus'),
    ('Tripodien aika', 'Tripodien aika'),
    ('Tuhat kerrosta', 'Tuhat kerrosta'),
    ('Tulen ja jään laulu( osa)?', 'Tulen ja jään laulu'),
    ('Twisted Tales', 'Twisted Tales'),
    ('Tymoran kivi, osa', 'Tymoran kivi'),
    ('Tähdentekijä', 'Tähdentekijä'),
    ('Tähtisilmät', 'Tähtisilmät'),
    ('Tähtitrilogia', 'Tähtitrilogia'),
    ('Tähdet', 'Tähdet'),
    ('Ufo tapaus', 'Ufo tapaus'),
    ('Uljasmaa', 'Uljasmaa'),
    ('Unennäkijöiden(\s?(\d\.)\s?kirja)', 'Unennäkijät'),
    ('Unien ([a-zåäö]+) kirja', 'Unien kirja'),
    ('Universumien Tomu', 'Universumien Tomu'),
    ('Unohdettujen kirjojen hautausmaa', 'Unohdettujen kirjojen hautausmaa'),
    ('Ursiini-trilogia', 'Ursiini-trilogia'),
    ('Usvasyntyinen', 'Usvasyntyinen'),
    ('Uuden auringon kirja', 'Uuden auringon kirja'),
    ('Vaanila', 'Vaanila'),
    ('Valhallan tarinoita', 'Valhallan tarinoita'),
    ('Valinta-sarja', 'Valinta-sarja'),
    ('Valitse oma seikkailusi( -sarja)?', 'Valitse oma seikkailusi -sarja'),
    ('Valitun aikakirjat', 'Valitun aikakirjat'),
    ('Valkolilja', 'Valkolilja'),
    ('Valo-sarja', 'Valo-sarja'),
    ('Valon ja varjon tarinoita', 'Valon ja varjon tarinoita'),
    ('Valtakivien taru', 'Valtakivien taru'),
    ('Valtakunta', 'Valtakunta'),
    ('Vampiraatit', 'Vampiraatit'),
    ('Vampyyripäiväkirjat', 'Vampyyripäiväkirjat'),
    ('Vampyyrisiskokset', 'Vampyyrisiskokset'),
    ('Varjojen kaupungit', 'Varjojen kaupungit'),
    ('Varjojen leikki', 'Varjojen leikki'),
    ('Varjojen marssi', 'Varjojen marssi'),
    ('Varjometsästäjät', 'Varjometsästäjät'),
    ('Varjo-sarja', 'Varjo'),
    ('Velhonuoret', 'Velhonuoret'),
    ('Veren kirjat', 'Veren kirjat'),
    ('Veren viemät', 'Veren viemät'),
    ('Vihreä varis( -sarja)?', 'Vihreä varis -sarja'),
    ('Viides tuuli', 'Viides tuuli'),
    ('Viillot', 'Viillot'),
    ('Viimeinen illuusio', 'Viimeinen illuusio'),
    ('Viimeinen', 'Viimeinen'),
    ('Viisi vartijaa, ([a-zA-ZäöåÄÖÅ]+\skirja)', 'Viisi vartijaa'),
    ('Vion Tarinat', 'Vion Tarinat'),
    ('Vuorileijonan varjo', 'Vuorileijonan varjo'),
    ('Vuorileijonan varjo -trilogia', 'Vuorileijonan varjo -trilogia'),
    ('Väkiveriset', 'Väkiveriset'),
    ('Väki', 'Väki'),
    ('W.A.R.P.', 'W.A.R.P.'),
    ('W.I.T.C.H.( -sarja)?', 'W.I.T.C.H. -sarja'),
    ('Waverly Placen velhot', 'Waverly Placen velhot'),
    ('Xenogenesis-trilogia', 'Xenogenesis-trilogia'),
    ('Yelena Zaltana', 'Yelena Zaltana'),
    ('Yön ja päivän välissä', 'Yön ja päivän välissä'),
    ('Yön siivet', 'Yön siivet'),
    ('Yön talo', 'Yön talo'),
    ('Zone 5 -sarja', 'Zone 5 -sarja'),
    ('Klaanien synty', 'Klaanien synty')
    ]
