pubseries = [
    ('10 mk:n romaaneja', '10 mk:n romaaneja'),
    ('10 mk:n sarja', '10 mk:n sarja'),
    ('50 pennin kirjasto', '50 pennin kirjasto'),
    ('A-sarja', 'A-sarja'),
    ('Action-sarja', 'Action-sarja'),
    ('Agentti-sarja', 'Agentti-sarja'),
    ('Aikamme kertojat -sarja', 'Aikamme kertojat -sarja'),
    ('Alexandre Dumasin historialliset romaanit', 'Alexandre Dumasin historialliset romaanit'),
    ('Arena-kirja', 'Arena-kirja'),
    ('Arena-sarja', 'Arena-sarja'),
    ('Basam Books klassikko -sarja', 'Basam Books klassikko -sarja'),
    ('Basam Shakti -sarja', 'Basam Shakti -sarja'),
    ('Best Books -sarja', 'Best Books -sarja'),
    ('Best Seller', 'Best Seller'),
    ('Book Studio -kirjat', 'Book Studio -kirjat'),
    ('Collector [Aa]ntologia', 'Collector Antologia'),
    ('Delfiini-kirjasto', 'Delfiini-kirjasto'),
    ('Elävä maailmankirjallisuus', 'Elävä maailmankirjallisuus'),
    ('Englantilaisia romaaneja', 'Englantilaisia romaaneja'),
    ('Eurooppa-sarja', 'Eurooppa-sarja'),
    ('FAN-sarja', 'FAN-sarja'),
    ('FBH-sarja', 'FBH-sarja'),
    ('Fantasiasarja', 'Fantasiasarja'),
    ('Fantasy-sarja', 'Fantasy-sarja'),
    ('Galax-sarja', 'Galax-sarja'),
    ('(Galaxy|GALAXY) [Ss]cifi( )?(-sarja)?', 'GALAXY Scifi'),
    ('Gummeruksen [Nn]uorten [Kk]irjasto', 'Gummeruksen Nuorten Kirjasto'),
    ('Gummeruksen nuortenkirjoja', 'Gummeruksen nuortenkirjoja'),
    ('H.P. Lovecraftin kootut teokset', 'H.P. Lovecraftin kootut teokset'),
    ('Helmi-sarja', 'Helmi-sarja'),
    ('Helsingin Kaiun kertomuskokoelma', 'Helsingin Kaiun kertomuskokoelma'),
    ('Horisontti-sarja', 'Horisontti-sarja'),
    ('Horror-sarja', 'Horror-sarja'),
    ('Hyvää ajanvietettä -sarja', 'Hyvää ajanvietettä -sarja'),
    ('Hämärän rajoilla -sarja', 'Hämärän rajoilla -sarja'),
    ('Isot keltaiset -sarja', 'Isot keltaiset -sarja'),
    ('Jalavan Fantasiasarja', 'Jalavan Fantasiasarja'),
    ('Jalavan SciFi-sarja', 'Jalavan SciFi-sarja'),
    ('Jalavan [Kk]auhusarja', 'Jalavan [Kk]auhusarja'),
    ('Jep-sarja', 'Jep-sarja'),
    ('Joka kodin tähtikirjasto', 'Joka kodin tähtikirjasto'),
    ('Joutoaikoina', 'Joutoaikoina'),
    ('Joutohetkinä', 'Joutohetkinä'),
    ('Jules Vernen romaanit', 'Jules Vernen romaanit'),
    ('Junior Scifi', 'Junior Scifi'),
    ('Kansanvallan näytelmistö', 'Kansanvallan näytelmistö'),
    ('Neuvostokirjallisuutta-sarja', 'Neuvostokirjallisuutta-sarja'),
    ('Kariston 10 mk:n romaaneja', 'Kariston 10 mk:n romaaneja'),
    ('Kariston 50 pennin romaaneja', 'Kariston 50 pennin romaaneja'),
    ('Kariston klassillinen kirjasto', 'Kariston klassillinen kirjasto'),
    ('Kariston nuoriso(n)?kirjoja', 'Kariston nuorisonkirjoja'),
    ('Kariston nuortenkirjasto', 'Kariston nuortenkirjasto'),
    ('Karis(t)?on nuortenkirjoja', 'Kariston nuortenkirjoja'),
    ('Kariston(n)? romaanisarja', 'Kariston romaanisarja'),
    ('Kauhujuttu-sarja', 'Kauhujuttu-sarja'),
    ('Kauhukabinetti-sarja', 'Kauhukabinetti-sarja'),
    ('Kauhusarja', 'Kauhusarja'),
    ('Kauhutarinoita', 'Kauhutarinoita'),
    ('Keijut-sarja', 'Keijut-sarja'),
    ('Keltainen kirjasto', 'Keltainen kirjasto'),
    ('Keltanokka-sarja', 'Keltanokka-sarja'),
    ('Keskiyön kirjasto( -sarja)?', 'Keskiyön kirjasto'),
    ('Kirjakerho lasten kirjapaketti', 'Kirjakerho lasten kirjapaketti'),
    ('Kirjan "parhaita nuorisokirjoja"', 'Kirjan "parhaita nuorisokirjoja"'),
    ('Kirjayhtymän science fiction-sarja', 'Kirjayhtymän science fiction-sarja'),
    ('Klassikko-sarja', 'Klassikko-sarja'),
    ('Kolibri-kirjasto', 'Kolibri-kirjasto'),
    ('Kolmen tähden sarja', 'Kolmen tähden sarja'),
    ('Kontakti-sarja', 'Kontakti-sarja'),
    ('Kotien suurromaanit( -sarja)?', 'Kotien suurromaanit'),
    ('Koululaiset kirjoittavat koululaisille', 'Koululaiset kirjoittavat koululaisille'),
    ('Koululaiskirjasto', 'Koululaiskirjasto'),
    ('Krimi-sarja', 'Krimi-sarja'),
    ('Kuoriaiskirjat', 'Kuoriaiskirjat'),
    ('Kuukauden Action -sarja', 'Kuukauden Action -sarja'),
    ('Kyläkirjaston kuvalehti B-sarjan kirjoina', 'Kyläkirjaston kuvalehti B-sarjan kirjoina'),
    ('Kymmenen markan romaaneja', 'Kymmenen markan romaaneja'),
    ('Kyöpeli-sarja', 'Kyöpeli-sarja'),
    ('LIKE(-)?fantasia', 'LIKE fantasia'),
    ('Lasten oma kirjasto', 'Lasten oma kirjasto'),
    ('Lasten toivekirjasto', 'Lasten toivekirjasto'),
    ('Leija-sarja', 'Leija-sarja'),
    ('(Like|LIKE) [Ss]ci[Ff]i( -sarja)?', 'LIKE Scifi'),
    ('Like fantasia -sarja', 'LIKE fantasia'),
    ('Like kauhu -sarja', 'LIKE kauhu'),
    ('Like-Scifi-sarja', 'LIKE Scifi'),
    ('Loki-Kirjojen sf-sarja', 'Loki-Kirjojen sf-sarja'),
    ('Love kirjat -sarja', 'Love kirjat -sarja'),
    ('Lovecraftilaisia kertomuksia', 'Lovecraftilaisia kertomuksia'),
    ('Lukemisen pikkujättiläiset -sarja', 'Lukemisen pikkujättiläiset -sarja'),
    ('Lukupalat-sarja', 'Lukupalat-sarja'),
    ('Lukurengas(-sarja)?', 'Lukurenga'),
    ('M-kirjat-sarja', 'M-kirjat-sarja'),
    ('Maailman Parhaat Kertojat -sarja', 'Maailman Parhaat Kertojat -sarja'),
    ('Maailman parhaita nuorisonkirjoja', 'Maailman parhaita nuorisonkirjoja'),
    ('Mailta ja meriltä( -sarja)?', 'Mailta ja meriltä -sarja'),
    ('Meidän lasten kirjasto', 'Meidän lasten kirjasto'),
    ('Mikrosarja', 'Mikrosarja'),
    ('Minipokkari-sarja.', 'Minipokkari-sarja.'),
    ('Moderneja kirjailijoita -sarja', 'Moderneja kirjailijoita -sarja'),
    ('Musta kaista', 'Musta kaista'),
    ('Musta virta -scifi', 'Musta virta -scifi'),
    ('Mysteeri-sarja', 'Mysteeri-sarja'),
    ('Neuvostokirjallisuutta-sarja', 'Neuvostokirjallisuutta-sarja'),
    ('Neuvostonovelleja-sarja', 'Neuvostonovelleja-sarja'),
    ('Nobel-sarja', 'Nobel-sarja'),
    ('Nocturne-sarja', 'Nocturne-sarja'),
    ('Nuorten 10 mk:n sarja', 'Nuorten 10 mk:n sarja'),
    ('Nuorten kirjaseura', 'Nuorten kirjaseura'),
    ('Nuorten kirjasto', 'Nuorten kirjasto'),
    ('Nuorten kirjoja', 'Nuorten kirjoja'),
    ('Nuorten minipokkarit', 'Nuorten minipokkarit'),
    ('Nuorten novellisto -sarja', 'Nuorten novellisto -sarja'),
    ('Nuorten parhaat -sarja', 'Nuorten parhaat -sarja'),
    ('Nuorten sarja', 'Nuorten sarja'),
    ('Nuorten toivekirjasto', 'Nuorten toivekirjasto'),
    ('Nykyromaaneja', 'Nykyromaaneja'),
    ('Otavan 50 p(enni)?(:)?n kirjasto', 'Otavan 50 pennin kirjasto'),
    ('Otavan fantasiaromaani', 'Otavan fantasiaromaani'),
    ('Otavan kirjasto -sarja', 'Otavan kirjasto -sarja'),
    ('Otavan nuortenkirjoja( )?(-sarja)?', 'Otavan nuortenkirjoja -sarja'),
    ('Otavan romaanisarja', 'Otavan romaanisarja'),
    ('Otavan uusi romaanisarja', 'Otavan uusi romaanisarja'),
    ('Otavan( )?kirjasto', 'Otavan( )?kirjasto'),
    ('Paletin Salama-sarja', 'Paletin Salama-sarja'),
    ('Paletin nuoriso -sarja', 'Paletin nuoriso -sarja'),
    ('Paranormaali', 'Paranormaali'),
    ('Parhaita nuorison kirjoja -sarja', 'Parhaita nuorison kirjoja -sarja'),
    ('Perettin seikkailusarja', 'Perettin seikkailusarja'),
    ('Pieni kirjasto', 'Pieni kirjasto'),
    ('Poikain jännityskirjasto', 'Poikain jännityskirjasto'),
    ('Poikien kirjasto', 'Poikien kirjasto'),
    ('Poikien sarja', 'Poikien sarja'),
    ('Poikien seikkailukirjasto', 'Poikien seikkailukirjasto'),
    ('Poikien sininen sarja', 'Poikien sininen sarja'),
    ('Pokkaristo-sarja', 'Pokkaristo-sarja'),
    ('Portti kirjat', 'Portti kirjat'),
    ('Nuorten kirjoja, uusi sarja', 'Nuorten kirjoja, uusi sarja'),
    ('Portti(-)?kirjat', 'Portti-kirjat'),
    ('Raketti-sarja', 'Raketti-sarja'),
    ('Ruotsalaisia tieteistarinoita', 'Ruotsalaisia tieteistarinoita'),
    ('Ruusu-Risti-Kirjasto', 'Ruusu-Risti-Kirjasto'),
    ('SAPO-sarja', 'SAPO-sarja'),
    ('Sapo', 'Sapo'),
    ('Satujen ja tarujen maailma -sarja', 'Satujen ja tarujen maailma -sarja'),
    ('Satupirtti', 'Satupirtti'),
    ('Saturnus SciFi -sarja', 'Saturnus SciFi -sarja'),
    ('Savukeitaan kauhuklassikot', 'Savukeitaan kauhuklassikot'),
    ('Savukeitaan maailman nykyrunouden sarja', 'Savukeitaan maailman nykyrunouden sarja'),
    ('Sci-fi -sarja', 'Sci-fi -sarja'),
    ('SciFi-sarja', 'SciFi-sarja'),
    ('Science Fiction -sarja', 'Science Fiction -sarja'),
    ('Scifin parhaita -sarja', 'Scifin parhaita -sarja'),
    ('Seaflowerin Classics -sarja', 'Seaflowerin Classics -sarja'),
    ('Seikkailu-sarja', 'Seikkailu-sarja'),
    ('Seikkailujen maailma( -sarja)?', 'Seikkailujen maailma -sarja'),
    ('Seikkailukirjasto', 'Seikkailukirjasto'),
    ('Seikkailuromaaneja', 'Seikkailuromaaneja'),
    ('Seikkailusarja', 'Seikkailusarja'),
    ('Seitsentähden-sarja', 'Seitsentähden-sarja'),
    ('Shokki', 'Shokki'),
    ('Shokki-sarja', 'Shokki-sarja'),
    ('Shokki-sarja', 'Shokki-sarja'),
    ('Silmukka-sarja', 'Silmukka-sarja'),
    ('Siniset-sarja', 'Siniset-sarja'),
    ('Sirius-sarja', 'Sirius-sarja'),
    ('Soundi-kirjat', 'Soundi-kirjat'),
    ('Suomalaisen kirjallisuuden klassikoita -sarja', 'Suomalaisen kirjallisuuden klassikoita -sarja'),
    ('Suomalaisia aavenovelleja', 'Suomalaisia aavenovelleja'),
    ('Suomalaisia aikamatkanovelleja', 'Suomalaisia aikamatkanovelleja'),
    ('Suomalaisia lohikäärmetarinoita', 'Suomalaisia lohikäärmetarinoita'),
    ('Suomen dekkariseuran julkaisusarja', 'Suomen dekkariseuran julkaisusarja'),
    ('Suomen kansan kirjakerhon romaaneja', 'Suomen kansan kirjakerhon romaaneja'),
    ('Suomen lasten kirjoja', 'Suomen lasten kirjoja'),
    ('Suuri [Nn]uorten [Kk]irjakerho -sarja', 'Suuri Nuorten Kirjakerho -sarja'),
    ('Suurten kertojain teoksia', 'Suurten kertojain teoksia'),
    ('Tam [Tt]am -kirja(t)?', 'Tam Tam -kirjat'),
    ('Tam tam -sarja', 'Tam Tam -kirjat'),
    ('Tammen nuortenkirjat -sarja', 'Tammen nuortenkirjat -sarja'),
    ('Taskutieto', 'Taskutieto'),
    ('Taskutoveri', 'Taskutoveri'),
    ('Tieteisromaani-sarja', 'Tieteisromaani-sarja'),
    ('Tieteissarja', 'Tieteissarja'),
    ('Tiikeri-sarja', 'Tiikeri-sarja'),
    ('Trendi-klassikot -sarja', 'Trendi-klassikot -sarja'),
    ('Tuhansille kodeille tuhatjärvien maassa', 'Tuhansille kodeille tuhatjärvien maassa'),
    ('Työväen kirjarengas', 'Työväen kirjarengas'),
    ('Tähtisarja', 'Tähtisarja'),
    ('Ursan sf-sarja', 'Ursan sf-sarja'),
    ('Uusia [Rr]omaaneja', 'Uusia Romaaneja'),
    ('Vaasan nuorisokirjat', 'Vaasan nuorisokirjat'),
    ('Valikoima kummituskertomuksia', 'Valikoima kummituskertomuksia'),
    ('Valiokirjasto', 'Valiokirjasto'),
    ('Valittuja tieteiskertomuksia', 'Valittuja tieteiskertomuksia'),
    ('Vaskikirjojen sf-kirjat', 'Vaskikirjojen sf-kirjat'),
    ('Viiden markan romaaneja', 'Viiden markan romaaneja'),
    ('Välipalaksi', 'Välipalaksi'),
    ('W.S.O.Y:N näytelmäsarja n:o', 'W.S.O.Y:N näytelmäsarja n:o'),
    ('W.S.O.Y:n koululaiskirjasto', 'W.S.O.Y:n koululaiskirjasto'),
    ('WSOY Pokkari', 'WSOY Pokkari'),
    ('Weilin\+Göösin [Kk]irjasto', 'Weilin+Göösin Kirjasto'),
    ('Weilin\+Göösin kirjasto', 'Weilin+Göösin Kirjasto'),
    ('m-novellit scifi -sarja', 'm-novellit scifi -sarja')]

bookseries = [
    ('5. aalto, osa', '5. aalto, osa'),
    ('A. Conan Doylen kootut kertomukset', 'A. Conan Doylen kootut kertomukset'),
    ('A. Conan Doylen kootut teokset', 'A. Conan Doylen kootut teokset'),
    ('Aavehevoset', 'Aavehevoset'),
    ('Aavekaksoset-sarja', 'Aavekaksoset-sarja'),
    ('Aavetaajuus-kirjat', 'Aavetaajuus-kirjat'),
    ('Abadazad', 'Abadazad'),
    ('Abarat', 'Abarat'),
    ('Across the Universe', 'Across the Universe'),
    ('Aikavartio', 'Aikavartio'),
    ('Ajan Pyörä(n)?( \d+\.)?( osa)?(Johdanto-osa)?', 'Ajan Pyörä'),
    ('Alismaan tarinat', 'Alismaan tarinat'),
    ('Alvinin (.+) kirja', 'Alvinin kirja'),
    ('Amberin kronikat', 'Amberin kronikat'),
    ('Ami-kirjat', 'Ami-kirjat'),
    ('Animorphs(: Megamorphs)?', 'Animorphs'),
    ('Avaruuden arvoitukset', 'Avaruuden arvoitukset'),
    ('Baabel', 'Baabel'),
    ('Bartimeus-trilogia', 'Bartimeus-trilogia'),
    ('Belgarionin taru', 'Belgarionin taru'),
    ('Bob Moran -sarja', 'Bob Moran -sarja'),
    ('Buster Bayliss', 'Buster Bayliss'),
    ('Canopus Argossa( )?(-sarja)', 'Canopus Argossa -sarja'),
    ('Charmed - Siskoni on noita -sarja', 'Charmed - Siskoni on noita -sarja'),
    ('Chrestomancin maailmat', 'Chrestomancin maailmat'),
    ('Danny Dunn\s?-sarja', 'Danny Dunn -sarja'),
    (r'David & Larissa', 'David & Larissa'),
    ('Deltoran vyö', 'Deltoran vyö'),
    ('Demonisodat-sarja', 'Demonisodat-sarja'),
    ('Deptfordin hiirten seikkailuja', 'Deptfordin hiirten seikkailuja'),
    ('Deverryn taru', 'Deverryn taru'),
    ('Doctor Who', 'Doctor Who'),
    ('Dorsai-trilogia', 'Dorsai-trilogia'),
    ('DragonLance - Kuolemanportti', 'DragonLance - Kuolemanportti'),
    ('DragonLance - Minotaurisodat', 'DragonLance - Minotaurisodat'),
    ('DragonLance kronikat', 'DragonLance kronikat'),
    ('DragonLance legendat', 'DragonLance legendat'),
    ('DragonLance-sarja, Dhamon-saaga', 'DragonLance-sarja, Dhamon-saaga'),
    ('Dragonlance Saga -sarja', 'Dragonlance Saga -sarja'),
    ('Dramoja', 'Dramoja'),
    ('Drenain tarut', 'Drenain tarut'),
    ('Elben taru', 'Elben taru'),
    ('Eleniumin taru', 'Eleniumin taru'),
    ('Ella Aura', 'Ella Aura'),
    ('Elminster-saaga', 'Elminster-saaga'),
    ('Eloonjääneet-sarja', 'Eloonjääneet-sarja'),
    ('Emily the Strange', 'Emily the Strange'),
    ('Engelsfors-trilogia', 'Engelsfors-trilogia'),
    ('Enkeliakatemia', 'Enkeliakatemia'),
    ('Ensimmäinen laki: osa', 'Ensimmäinen laki'),
    ('Ensimmäisen kuninkaan saaga,Etsijät', 'Ensimmäisen kuninkaan saaga,Etsijät'),
    ('Eteläraja-trilogia', 'Eteläraja-trilogia'),
    ('Eve Dallas( )?(-sarja)?', 'Eve Dallas -sarja'),
    ('Everworld', 'Everworld'),
    ('Faunoidit', 'Faunoidit'),
    ('O\'Dwyerin serkut', 'O\'Dwyerin serkut'),
    ('Fionavarin kuvakudos', 'Fionavarin kuvakudos'),
    ('Flash Gordon( -sarja)?', 'Flash Gordon'),
    ('Forgotten Realms. Drowin tytär', 'Forgotten Realms. Drowin tytär'),
    ('Forgotten Realms. Drowprinsessa-sarja', 'Forgotten Realms. Drowprinsessa-sarja'),
    ('Forgotten Realms. Kuninkaita ja neuvonantajia', 'Forgotten Realms. Kuninkaita ja neuvonantajia'),
    ('Forgotten Realms. Laulut ja miekat', 'Forgotten Realms. Laulut ja miekat'),
    ('Gigi ja Henry', 'Gigi ja Henry'),
    ('Goosebumps Kauhumaa', 'Goosebumps Kauhumaa'),
    ('Haaksirikkoiset', 'Haaksirikkoiset'),
    ('Hai-kirja', 'Hai-kirja'),
    ('Hard Core -sarja', 'Hard Core -sarja'),
    ('Harper Connelly -sarja', 'Harper Connelly -sarja'),
    ('Helppohintainen kirjasto', 'Helppohintainen kirjasto'),
    ('Hermux Tantamoqin seikkailuja', 'Hermux Tantamoqin seikkailuja'),
    ('Horror-sarja', 'Horror-sarja'),
    ('Hurjien tarinoiden talo', 'Hurjien tarinoiden talo'),
    ('Idhunin kronikat', 'Idhunin kronikat'),
    ('Ihmemaa Oz', 'Ihmemaa Oz'),
    ('Ikikesä, osa', 'Ikikesä, osa'),
    ('Ilmestyneiden taru', 'Ilmestyneiden taru'),
    ('Iso-Werneri-sarja', 'Iso-Werneri-sarja'),
    ('Jack Sparrow', 'Jack Sparrow'),
    ('Jenny Dean -sarja', 'Jenny Dean -sarja'),
    ('Jep-sarja', 'Jep-sarja'),
    ('Jäämaan kronikka', 'Jäämaan kronikka'),
    ('Jäätuulen laakso -trilogia osa', 'Jäätuulen laakso -trilogia'),
    ('Kaaoksen aika', 'Kaaoksen aika'),
    ('Kaaoksen sota', 'Kaaoksen sota'),
    ('Kadonneet historiat', 'Kadonneet historiat'),
    ('Kadonneet kronikat osa', 'Kadonneet kronikat'),
    ('Kaikkeuden kirja', 'Kaikkeuden kirja'),
    ('Kaikkeuden kivi', 'Kaikkeuden kivi'),
    ('Kalmanväreitä-sarja', 'Kalmanväreitä-sarja'),
    ('Kanen aikakirjat', 'Kanen aikakirjat'),
    ('Kangin rykmentti', 'Kangin rykmentti'),
    ('Kapinaenkelit', 'Kapinaenkelit'),
    ('Kauhuagentti Nelli Rapp', 'Kauhuagentti Nelli Rapp'),
    ('Kauhukartano', 'Kauhukartano'),
    ('Keihäänkantajan taru', 'Keihäänkantajan taru'),
    ('Kirja aikojen alusta', 'Kirja aikojen alusta'),
    ('Kivistänäkijät osa', 'Kivistänäkijät osa'),
    ('Kontakti-kirja', 'Kontakti-kirja'),
    ('Korpinkehät', 'Korpinkehät'),
    ('Korppi-sarja', 'Korppi-sarja'),
    ('Korppikartanon salat', 'Korppikartanon salat'),
    ('Kotka-sarja', 'Kotka-sarja'),
    ('Kuikansulka-trilogia', 'Kuikansulka-trilogia'),
    ('Kultasiipien keijukoulu', 'Kultasiipien keijukoulu'),
    ('Kuninkaansurmaajan kronikka: ([a-zA-ZåäöÅÄÖ]+ päivä)', 'Kuninkaansurmaajan kronikka'),
    ('Kuolemanportti', 'Kuolemanportti'),
    ('Kuolemattoman Nicholas Flamelin salaisuudet', 'Kuolemattoman Nicholas Flamelin salaisuudet'),
    ('Kuolemattomat', 'Kuolemattomat'),
    ('Kuparisaari', 'Kuparisaari'),
    ('Kurki-sarja', 'Kurki-sarja'),
    ('Kvanttipainovoima', 'Kvanttipainovoima'),
    ('Kätkijät-sarja', 'Kätkijät-sarja'),
    ('Käärmesodan taru', 'Käärmesodan taru'),
    ('Lampun lapset', 'Lampun lapset'),
    ('Langenneet enkelit', 'Langenneet enkelit'),
    ('Langennut enkeli', 'Langennut enkeli'),
    ('Lankhmar osa', 'Lankhmar osa'),
    ('Lierolan kronikka osa', 'Lierolan kronikka'),
    ('Lohikäärmeakatemia', 'Lohikäärmeakatemia'),
    ('Lohikäärmelaakso', 'Lohikäärmelaakso'),
    ('Lohikäärmelaivat', 'Lohikäärmelaivat'),
    ('Lohikäärmeratsastaja', 'Lohikäärmeratsastaja'),
    ('Loihtijakronikka', 'Loihtijakronikka'),
    ('Lordi Kultainen', 'Lordi Kultainen'),
    ('Lumen ja jään maa', 'Lumen ja jään maa'),
    ('Lumoleipomo', 'Lumoleipomo'),
    ('Lumotun metsän kronikat', 'Lumotun metsän kronikat'),
    ('Maailmanjako', 'Maailmanjako'),
    ('Maameren tarinat', 'Maameren tarinat'),
    ('Maan lapset -sarja', 'Maan lapset -sarja'),
    ('MaddAddam-trilogia', 'MaddAddam-trilogia'),
    ('Magisterium', 'Magisterium'),
    ('Mahtavat', 'Mahtavat'),
    ('Mallorean taru', 'Mallorean taru'),
    ('Manalan valtiaat', 'Manalan valtiaat'),
    ('Marie Corellin romaanit', 'Marie Corellin romaanit'),
    ('Mars-kirjat', 'Mars-kirjat'),
    ('Matkakirjallisuutta-sarja', 'Matkakirjallisuutta-sarja'),
    ('Megamorphs', 'Megamorphs'),
    ('Merlinin kronikat', 'Merlinin kronikat'),
    ('Metsästäjän miekat', 'Metsästäjän miekat'),
    ('Mifonki-sarja', 'Mifonki-sarja'),
    ('Monsterijengi', 'Monsterijengi'),
    ('Muinainen pimeys', 'Muinainen pimeys'),
    ('Murroskaudet', 'Murroskaudet'),
    ('Musta Haltia -trilogia osa', 'Musta Haltia -trilogia'),
    ('Musta komppania', 'Musta komppania'),
    ('Musta torni', 'Musta torni'),
    ('Mustamiekka', 'Mustamiekka'),
    ('Mustan tikarin veljeskunta', 'Mustan tikarin veljeskunta'),
    ('Mustien ruusujen maa', 'Mustien ruusujen maa'),
    ('Mystic City', 'Mystic City'),
    ('Myyttihovi', 'Myyttihovi'),
    ('Narnia-sarja', 'Narnia-sarja'),
    ('Neljäs piiri', 'Neljäs piiri'),
    ('Nicholas North', 'Nicholas North'),
    ('Nick Carter', 'Nick Carter'),
    ('Noitametsä-trilogia', 'Noitametsä-trilogia'),
    ('Noitien taistelu', 'Noitien taistelu'),
    ('Noituri', 'Noituri'),
    ('Nymfit', 'Nymfit'),
    ('Näkijän taru', 'Näkijän taru'),
    ('Nälkäpeli', 'Nälkäpeli'),
    ('O.K.-sarja', 'O.K.-sarja'),
    ('Olympoksen sankarit', 'Olympoksen sankarit'),
    ('Oman keisarien aikakirjat', 'Oman keisarien aikakirjat'),
    ('Onttujen ([a-zåäöA-ZÅÄÖ]+ kirja)', 'Onttujen kirja'),
    ('Orrin', 'Orrin'),
    ('Oswald Bastable', 'Oswald Bastable'),
    ('Painajaisia ja unikuvia', 'Painajaisia ja unikuvia'),
    ('Palkkasoturit [I]+ kirja', 'Palkkasoturit'),
    ('Pappiskvintetti - osa', 'Pappiskvintetti'),
    ('Partholon', 'Partholon'),
    ('Pekka Lipponen ja Kalle-Kustaa Korkki', 'Pekka Lipponen ja Kalle-Kustaa Korkki'),
    ('Pekka Lipposen seikkailuja', 'Pekka Lipposen seikkailuja'),
    ('Pellucidar', 'Pellucidar'),
    ('Pendergast-sarja', 'Pendergast-sarja'),
    ('Percy Jackson', 'Percy Jackson'),
    ('Perillinen', 'Perillinen'),
    ('Pernin lohikäärmeritarit', 'Pernin lohikäärmeritarit'),
    ('Pimeyden ihmeet', 'Pimeyden ihmeet'),
    ('Pimeyden oppilas osa', 'Pimeyden oppilas'),
    ('Pimeyden polut -sarja', 'Pimeyden polut -sarja'),
    ('Pitkä Maa', 'Pitkä Maa'),
    ('Pohjankontu', 'Pohjankontu'),
    ('Pohjoiset ennustukset', 'Pohjoiset ennustukset'),
    ('Pollux-hevoskerho( )?-sarja', 'Pollux-hevoskerho -sarja'),
    ('Profeetan ruusu( osa)?', 'Profeetan ruusu'),
    ('Pronssikronikat', 'Pronssikronikat'),
    ('Pronssisoturit', 'Pronssisoturit'),
    ('Punainen sulka -sarja', 'Punainen sulka -sarja'),
    ('Pyhimys-sarja', 'Pyhimys-sarja'),
    ('R.A. Salvatoren Lukkikuningattaren sota(, osa)?', 'R.A. Salvatoren Lukkikuningattaren sota'),
    ('Rakkaus ei katso aikaa', 'Rakkaus ei katso aikaa'),
    ('Redwallin taru', 'Redwallin taru'),
    ('Remnants - Selviytyjät Maasta', 'Remnants - Selviytyjät Maasta'),
    ('Replica', 'Replica'),
    ('Replica, Geeni-trilogia', 'Replica, Geeni-trilogia'),
    ('Revontulitalli-sarja', 'Revontulitalli-sarja'),
    ('Roswell High', 'Roswell High'),
    ('Salaiset kansiot - [Tt]he X-Files -sarja', 'Salaiset kansiot - The X-Files -sarja'),
    ('Sammon vartijat', 'Sammon vartijat'),
    ('Satumaa', 'Satumaa'),
    ('Scott Saunders -sarja', 'Scott Saunders -sarja'),
    ('Selviytyjät', 'Selviytyjät'),
    ('Septimus Heap', 'Septimus Heap'),
    ('Sexton Blake -sarja', 'Sexton Blake -sarja'),
    ('Shamaanilegendat', 'Shamaanilegendat'),
    ('Shannaran jälkeläiset', 'Shannaran jälkeläiset'),
    ('Shannaran perintö', 'Shannaran perintö'),
    ('Sielujen sota', 'Sielujen sota'),
    ('Sihis', 'Sihis'),
    ('Siskoni vampyyri', 'Siskoni vampyyri'),
    ('Solamnian nousu', 'Solamnian nousu'),
    ('Sookie Stackhouse', 'Sookie Stackhouse'),
    ('Soturikissat', 'Soturikissat'),
    ('Soturikissat erikoisseikkailu', 'Soturikissat erikoisseikkailu'),
    ('Soturikissat, Kolmikon mahti', 'Soturikissat, Kolmikon mahti'),
    ('Soturikissat, Uusi profetia', 'Soturikissat, Uusi profetia'),
    ('Spiderwickin kronikat', 'Spiderwickin kronikat'),
    ('Spiraalipuutarha-sarja', 'Spiraalipuutarha-sarja'),
    ('Star Wars', 'Star Wars'),
    ('Star Wars - EpisodiStar Wars - Jedioppilas', 'Star Wars - EpisodiStar Wars - Jedioppilas'),
    ('Star Wars - Jeditehtävä', 'Star Wars - Jeditehtävä'),
    ('Star Wars( )?-sarja', 'Star Wars -sarja'),
    ('Suojelijoiden tähti( osa)?', 'Suojelijoiden tähti'),
    ('Susiraja', 'Susiraja'),
    ('Sysimetsän kronikat', 'Sysimetsän kronikat'),
    ('Syysmaa', 'Syysmaa'),
    ('Särkynyt meri', 'Särkynyt meri'),
    ('Taikakoirat', 'Taikakoirat'),
    ('Taikavaras', 'Taikavaras'),
    ('Taistelija-sarja', 'Taistelija-sarja'),
    ('Taistelupeli-sarja', 'Taistelupeli-sarja'),
    ('Tamulin taru', 'Tamulin taru'),
    ('Tarinoita Maan reunalta', 'Tarinoita Maan reunalta'),
    ('Taru kolmesta miekasta', 'Taru kolmesta miekasta'),
    ('Tarzan-kirjat', 'Tarzan-kirjat'),
    ('Tauno Karilaan valitut seikkailukertomukset', 'Tauno Karilaan valitut seikkailukertomukset'),
    ('Taynikma', 'Taynikma'),
    ('The Nightmare Room( -trilogia)?', 'The Nightmare Room -trilogia'),
    ('The Walking Dead', 'The Walking Dead'),
    ('Tiger Team', 'Tiger Team'),
    ('Tulen ja jään laulu osa', 'Tulen ja jään laulu'),
    ('Tymoran kivi, osa', 'Tymoran kivi'),
    ('Tähtisilmät', 'Tähtisilmät'),
    ('Unennäkijöiden(\s?(\d\.)\s?kirja)', 'Unennäkijät'),
    ('Unien ([a-zåäö]+) kirja', 'Unien kirja'),
    ('Universumien Tomu', 'Universumien Tomu'),
    ('Uuden auringon kirja', 'Uuden auringon kirja'),
    ('Valhallan tarinoita', 'Valhallan tarinoita'),
    ('Valitse oma seikkailusi( -sarja)?', 'Valitse oma seikkailusi -sarja'),
    ('Valo-sarja', 'Valo-sarja'),
    ('Vampiraatit', 'Vampiraatit'),
    ('Vampyyripäiväkirjat', 'Vampyyripäiväkirjat'),
    ('Vampyyrisiskokset', 'Vampyyrisiskokset'),
    ('Varjojen kaupungit', 'Varjojen kaupungit'),
    ('Varjojen leikki', 'Varjojen leikki'),
    ('Varjojen marssi', 'Varjojen marssi'),
    ('Velhonuoret', 'Velhonuoret'),
    ('Vihreä varis( -sarja)?', 'Vihreä varis -sarja'),
    ('Viisi vartijaa, ([a-zA-ZäöåÄÖÅ]+\skirja)', 'Viisi vartijaa'),
    ('Voittaja-sarja', 'Voittaja-sarja'),
    ('Vuorileijonan varjo', 'Vuorileijonan varjo'),
    ('Vuorileijonan varjo -trilogia', 'Vuorileijonan varjo -trilogia'),
    ('W.A.R.P.', 'W.A.R.P.'),
    ('W.I.T.C.H.( -sarja)?', 'W.I.T.C.H. -sarja'),
    ('Waverly Placen velhot', 'Waverly Placen velhot'),
    ('Yön talo', 'Yön talo'),
    ('Zone 5 -sarja', 'Zone 5 -sarja')]
