subtitles = [
        'Näytelmä 3:ssa näytöksessä',
        'Mielikuvitusromaani Ameriikan ja Avaruuden ihmemaailmoista',
        'Kuusi tositapausta',
        'Tarinoita elävistä kuolleista ja Suomesta',
        'Algot Primuksen lentävä avaruushuoltoasema',
        'Kertomuksia täältä ja muualta',
        'Sulon ja Tildan seikkailut Hiidenharjussa',
        'Aavemaisia tarinoita',
        'Matkustus 97:ssä tunnissa',
        r'''Kertomus hiirestä, prinsessasta, keitosta ja
        lankarullasta.''',
        r'''Kreivi Cagliostron muistelmat sekä hänen muistiinpanonsa \
        keskusteluista Aristoteleen, Danten, Puskinin, Einsteinin ja monien muiden \
        aikalaisten kanssa.''',
        '''Okkulttisia etsivätarinoita.'''
        r'''Kertomuksia täältä ja muualta.''',
        'Matka ajan halki',
        'Herrasmiesroistojen ensimmäinen tarina',
        'Tarinoita toisista todellisuuksista',
        'Kertomus parvista',
        'Kolmiosainen okkultinen romaani',
        'Lumoavaa vampyyrierotiikkaa',
        'Ikuisen päivän maa',
        'Pelastakaa kansanedustaja Makkonen',
        'Yksinäytöksinen huvinäytelmä',
        'Kolminäytöksinen näytelmä',
        'Seikkailu toisessa maailmassa',
        'Okkulttisia etsivätarinoita',
        'Kryptozoologisia novelleja',
        'Suomalaisia Cthulhu-tarinoita',
        'Suomalaisia ihmissusinovelleja',
        'Vanhoja suomalaisia kauhutarinoita',
        'Vanhoja suomalaisia kauhunovelleja',
        'Ikivillien tarina',
        'Satujen ja tarujen maailma',
        'Groteskia virolaista proosaa',
        'Antikvariaattitarinoita',
        'Japanin kummitustarinoita',
        'Modernin fantasian antologia',
        '|Kertomuksia yliluonnollisista aiheista'
        ]
