-- Static seed for suomisf.award_import_source (derived from ISFDB).
-- Apply on any server WITHOUT scraping ISFDB; award ids are shared
-- across environments. Idempotent: clears and repopulates the table.
BEGIN;
TRUNCATE suomisf.award_import_source;
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (2, 261, 0, 'Paras romaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (2, 262, 2, 'Paras pitkä novelli');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (3, 413, 0, 'Paras romaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (3, 414, 1, 'Paras pitkä novelli');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (3, 415, 2, 'Paras pienoisromaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (3, 418, 1, 'Paras novelli');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (3, 1029, 0, 'Paras nuorten sf-romaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (4, 329, 0, 'Paras antologia');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (4, 338, 0, 'Paras kokoelma');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (4, 347, 0, 'Paras fantasiaromaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (4, 349, 0, 'Paras ensiromaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (4, 350, 0, 'Paras kauhuromaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (4, 351, 0, 'Paras kauhu/synkkä fantasia -romaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (4, 360, 1, 'Paras pitkä novelli');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (4, 361, 2, 'Paras pienoisromaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (4, 375, 0, 'Paras scifi-romaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (4, 377, 1, 'Paras lyhyt fiktio');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (4, 378, 1, 'Paras novelli');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (4, 379, 0, 'Paras kokoelma');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (4, 382, 0, 'Paras nuortenkirja');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (5, 140, 0, 'Paras sf-romaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (6, 120, 0, 'Paras romaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (6, 121, 1, 'Paras lyhyt fiktio');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (6, 1028, 0, 'Paras nuortenkirja');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (6, 1096, 0, 'Paras kokoelma');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (7, 520, 0, 'Paras vaihtoehtoishistoria (pitkä muoto)');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (7, 521, 1, 'Paras vaihtoehtoishistoria (lyhyt muoto)');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (10, 130, 0, 'Paras sf-romaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (11, 423, 0, 'Paras romaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (12, 768, 1, 'Paras scifi-novelli');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (19, 528, 0, 'Paras antologia');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (19, 529, 0, 'Paras kokoelma');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (19, 531, 0, 'Paras kokoelma');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (19, 532, 0, 'Paras romaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (19, 533, 2, 'Paras pienoisromaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (19, 534, 1, 'Paras lyhyt fiktio');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (19, 667, 0, 'Paras pitkä fiktio');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (20, 496, 0, 'Paras kokoelma');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (20, 497, 0, 'Paras ensiromaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (20, 498, 0, 'Paras romaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (20, 499, 1, 'Paras pitkä novelli');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (20, 500, 2, 'Paras pienoisromaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (20, 503, 0, 'Paras nuortenkirja');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (20, 505, 0, 'Paras antologia');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (20, 507, 0, 'Paras pitkä fiktio');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (20, 510, 1, 'Paras lyhyt fiktio');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (20, 632, 0, 'Paras nuortenkirja');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (21, 400, 0, 'Paras romaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (21, 401, 0, 'Paras romaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (21, 402, 0, 'Paras lastenkirja');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (21, 1110, 0, 'Paras nuortenkirja');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (24, 618, 0, 'Carnegie-mitali');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (26, 75, 0, 'Paras romaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (26, 76, 0, 'Paras antologia');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (26, 80, 0, 'Paras kokoelma');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (26, 88, 2, 'Paras pienoisromaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (26, 89, 1, 'Paras lyhyt fiktio');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (26, 90, 1, 'Paras novelli');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (26, 585, 0, 'Paras fantasiaromaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (26, 586, 0, 'Paras kauhuromaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (27, 16, 0, 'Paras romaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (29, 730, 0, 'Paras fantasiaromaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (29, 731, 0, 'Paras scifi-romaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (29, 732, 0, 'Paras kauhuromaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (29, 733, 0, 'Paras nuorten sf-romaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (29, 734, 0, 'Paras lastenkirja');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (29, 735, 0, 'Paras nuorten sf-romaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (29, 736, 0, 'Paras paranormaali fantasia -romaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (29, 738, 0, 'Paras nuortenkirja');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (30, 439, 0, 'Paras romaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (30, 440, 1, 'Paras pitkä novelli');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (30, 441, 2, 'Paras pienoisromaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (30, 446, 1, 'Paras novelli');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (31, 286, 0, 'Paras nuortenkirja');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (31, 287, 1, 'Paras ulkomainen novelli');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (31, 288, 1, 'Paras novelli');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (31, 290, 0, 'Paras ulkomainen romaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (31, 292, 0, 'Paras romaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (31, 698, 0, 'Paras nuortenkirja');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (31, 699, 0, 'Paras ulkomainen nuortenromaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (32, 677, 0, 'Paras romaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (32, 678, 1, 'Paras novelli');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (32, 679, 2, 'Paras pienoisromaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (32, 680, 1, 'Paras lyhyt fiktio');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (32, 685, 0, 'Paras ulkomainen romaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (32, 686, 0, 'Paras ulkomainen romaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (32, 691, 1, 'Paras novelli');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (33, 745, 0, 'Paras romaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (33, 748, 0, 'Paras ulkomainen romaani');
INSERT INTO suomisf.award_import_source (award_id, isfdb_category_id, item_type, our_category) VALUES (33, 749, 1, 'Paras ulkomainen novelli');
COMMIT;
