"""
Generate tests/API_COVERAGE.md from a pytest-cov JSON report.

For every Flask route, looks up the view function in the coverage data and
reports whether any test reached it and how much of it ran. This replaces
the old hand-maintained coverage matrix, which drifted out of date.

Usage:
    pdm run pytest tests -m "not network" --cov=app --cov-branch \\
        --cov-report=json:coverage.json
    pdm run python tests/scripts/endpoint_coverage.py [coverage.json]
"""

import inspect
import json
import os
import sys
from collections import defaultdict
from datetime import date

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__))))
sys.path.insert(0, ROOT)
os.chdir(ROOT)
# Same as conftest: importing app loads a dotenv file; point it at the
# test DB config rather than production.
os.environ.setdefault('SUOMISF_DOTENV', '.env.e2e')

from app import app  # noqa: E402

OUTPUT = os.path.join(ROOT, 'tests', 'API_COVERAGE.md')
IGNORED_METHODS = {'HEAD', 'OPTIONS'}


def load_coverage(path: str) -> dict:
    with open(path, encoding='utf-8') as f:
        return json.load(f)


def view_coverage(cov: dict, func) -> tuple[str, str, float | None]:
    """Return (module file, function name, percent covered or None)."""
    func = inspect.unwrap(func)
    name = func.__qualname__
    source_file = inspect.getsourcefile(func)
    if source_file is None:
        return '?', name, None
    source = os.path.relpath(source_file, ROOT)
    functions = cov['files'].get(source, {}).get('functions', {})
    summary = functions.get(name, {}).get('summary')
    if summary is None or summary['num_statements'] == 0:
        return source, name, None
    percent = 100.0 * summary['covered_lines'] / summary['num_statements']
    return source, name, percent


def collect_routes(cov: dict) -> dict[str, list[dict]]:
    """Group routes by the module that defines the view."""
    by_module: dict[str, list[dict]] = defaultdict(list)
    for rule in app.url_map.iter_rules():
        if rule.endpoint == 'static':
            continue
        func = app.view_functions[rule.endpoint]
        source, name, percent = view_coverage(cov, func)
        methods = sorted((rule.methods or set()) - IGNORED_METHODS)
        by_module[source].append({
            'methods': ', '.join(methods),
            'rule': rule.rule,
            'view': name,
            'percent': percent,
        })
    for routes in by_module.values():
        routes.sort(key=lambda r: (r['rule'], r['methods']))
    return by_module


def status(percent: float | None) -> str:
    if percent is None:
        return '?'
    if percent == 0:
        return '❌'
    return '✅'


def render(cov: dict, by_module: dict[str, list[dict]]) -> str:
    routes = [r for rs in by_module.values() for r in rs]
    reached = [r for r in routes if r['percent']]
    totals = cov['totals']
    lines = [
        '# SuomiSF API Test Coverage',
        '',
        '<!-- Generated by tests/scripts/endpoint_coverage.py. '
        'Do not edit by hand. -->',
        '',
        f'**Generated:** {date.today().isoformat()}  ',
        f'**Routes:** {len(routes)}, reached by tests: {len(reached)} '
        f'({100 * len(reached) / len(routes):.0f}%)  ',
        f'**Line coverage of app/:** {totals["percent_covered"]:.1f}% '
        f'({totals["covered_lines"]} of {totals["num_statements"]} '
        'statements, branch coverage included)',
        '',
        'A route counts as reached when at least one test executed its view '
        'function. "View lines" is the share of the view function body that '
        'ran; it does not include the `impl_*` code the view calls, so a '
        'reached route can still have large untested paths. See the HTML '
        'coverage report for line-level detail.',
        '',
        '## Regenerating',
        '',
        '```bash',
        'pdm run pytest tests -m "not network" --cov=app --cov-branch \\',
        '    --cov-report=json:coverage.json --cov-report=html',
        'pdm run python tests/scripts/endpoint_coverage.py',
        '```',
        '',
        '## Not reached by any test',
        '',
    ]
    unreached = sorted((r for r in routes if not r['percent']),
                       key=lambda r: r['rule'])
    if unreached:
        lines += ['| Methods | Route | View |', '|---|---|---|']
        lines += [f'| {r["methods"]} | `{r["rule"]}` | `{r["view"]}` |'
                  for r in unreached]
    else:
        lines.append('None.')
    lines += ['', '## All routes by module', '']
    for source in sorted(by_module):
        file_cov = cov['files'].get(source, {}).get('summary', {})
        pct = file_cov.get('percent_covered')
        pct_str = f' — file {pct:.0f}% covered' if pct is not None else ''
        lines += [
            f'### `{source}`{pct_str}',
            '',
            '| | Methods | Route | View | View lines |',
            '|---|---|---|---|---|',
        ]
        for r in by_module[source]:
            pct_cell = '-' if r['percent'] is None else f'{r["percent"]:.0f}%'
            lines.append(
                f'| {status(r["percent"])} | {r["methods"]} | `{r["rule"]}` '
                f'| `{r["view"]}` | {pct_cell} |')
        lines.append('')
    return '\n'.join(lines)


def main() -> None:
    path = sys.argv[1] if len(sys.argv) > 1 else 'coverage.json'
    cov = load_coverage(path)
    by_module = collect_routes(cov)
    with open(OUTPUT, 'w', encoding='utf-8') as f:
        f.write(render(cov, by_module))
    print(f'Wrote {os.path.relpath(OUTPUT, ROOT)}')


if __name__ == '__main__':
    main()
